#!/usr/bin/env python3
import json, os

OUT = "/Users/kallolchakraborty/Proof Of Concepts/Quick Reference - GitHub Pages/content/patterns/engineering-patterns-staff.json"

def bd(label, color="#E95420"):
    bg = f"rgba({','.join(str(int(color[i:i+2],16)) for i in (1,3,5))},0.08)"
    return f'<div style="margin-bottom:16px"><span style="display:inline-block;background:{bg};border:1px solid {color};color:{color};font:700 10px system-ui;padding:3px 10px;border-radius:99px;letter-spacing:.05em">{label}</span></div>'

def mg(items):
    r = "".join(f'<div style="background:#f8fafc;border:1.5px solid #e2e8f0;border-radius:8px;padding:14px"><div style="font:700 22px system-ui;color:{c}">{v}</div><div style="font:11px system-ui;color:#64748b;margin-top:2px">{l}</div></div>' for v,l,c in items)
    return f'<div style="margin:16px 0;display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:10px">{r}</div>'

def tb(hd, rows):
    th = "".join(f'<th style="padding:10px 12px;border-bottom:2px solid #e2e8f0;color:#475569;font-weight:700">{h}</th>' for h in hd)
    tr = ""
    for i,r in enumerate(rows):
        bg = 'background:#fafafa' if i%2 else ''
        tr += f'<tr style="border-bottom:1px solid #f1f5f9;{bg}>' + "".join(f'<td style="padding:9px 12px{f";font-weight:600" if j==0 else ""}">{c}</td>' for j,c in enumerate(r)) + '</tr>'
    return f'<div style="margin:16px 0;overflow-x:auto"><table style="width:100%;border-collapse:collapse;font:12px system-ui,sans-serif"><thead><tr style="background:#f1f5f9;text-align:left">{th}</tr></thead><tbody>{tr}</tbody></table></div>'

S = []

S.append({
  "title": "1. The Staff+ Engineer Role: Scope, Impact & Expectations",
  "description": bd("STAFF+ ROLE · SCOPE · IMPACT · EXPECTATIONS", "#4285F4") + """<p><b>Staff+ expectation:</b> The Staff engineer title means different things at different companies, but the core is universal: you are responsible for technical outcomes across teams, not just your own code. Your leverage comes from influence, not authority.</p><p><b>Staff+ Archetypes (Tanya Reilly, "The Staff Engineer\u2019s Path"):</b></p><ul><li><b>Tech Lead:</b> Guides a single team, owns technical direction, unblocks engineers. Most common Staff entry point.</li><li><b>Architect:</b> Owns cross-team technical strategy. Designs systems that span multiple teams. Makes technology choices.</li><li><b>Solver:</b> Drops into the hardest problems. Debugs the undebuggable. Works across the org on the most critical issues.</li><li><b>Right Hand:</b> Works directly with director/VP. Translates business goals into technical strategy. Represents engineering in cross-functional meetings.</li></ul>""" + tb(["Dimension","Senior Engineer","Staff+ Engineer","Principal Engineer"],[["Scope","Your team","Your org (2-5 teams)","Company-wide"],["Time horizon","Weeks (sprint)","Quarters (OKRs)","Years (roadmap)"],["Primary work","Code + design","Strategy + influence","Vision + culture"],["Breadth","Deep in one area","Deep + broad across teams","Organizational breadth"],["Communication","Within team","Cross-team docs + presentations","Company-wide talks, exec comms"],["Mentorship","Pair programming","Sponsorship, career growth","Org-wide talent development"]]) + """<p><b>Staff+ Core Responsibilities:</b> (1) Technical direction: set the technical strategy for your area. (2) Project execution: unblock teams, make difficult tradeoff decisions. (3) People development: mentor senior engineers, create growth opportunities. (4) Culture: model engineering excellence, drive operational maturity. (5) Communication: write design docs, present to leadership, influence without authority.</p><p><b>Staff+ insight:</b> At most FAANGs, the Staff+ promotion requires demonstrating impact across at least 2-3 teams. Your promotion packet should show: concrete examples of cross-team influence, measurable business impact from technical decisions, and evidence of developing other engineers.</p>""",
  "codeBlock": ""
})

S.append({
  "title": "2. Technical Strategy: Writing, Communicating & Executing",
  "description": bd("STRATEGY · VISION · ROADMAP · EXECUTION", "#FF6600") + """<p><b>Staff+ expectation:</b> Technical strategy is the highest-leverage activity of a Staff+ engineer. A good strategy aligns engineering work with business goals, anticipates future needs, and creates clarity. A bad strategy is a list of projects.</p><p><b>What Makes a Good Technical Strategy:</b> (1) A clear diagnosis of the current situation ("our build system is too slow, causing 30% developer time lost to waiting"). (2) A guiding policy ("we will invest in remote caching and incremental builds"). (3) Coherent actions ("hire 2 build engineers, purchase remote cache infra from vendor X, migrate 5 key repos in Q2").</p><p><b>Strategy Document Structure (Google, Amazon):</b> Context (current state, problems, opportunities) -> Principles (3-5 decision-making rules that won\u2019t change) -> Vision (where we want to be in 12-18 months) -> Strategic bets (what we will and won\u2019t do) -> Roadmap (phased execution plan with owners) -> Risks (what could go wrong, mitigation).</p>""" + tb(["Bad Strategy","Good Strategy"],[["A list of projects everyone wants","A diagnosis of a specific problem + a coherent response"],["Vague principles (be agile, be reliable)","Specific, testable principles (p99 latency < 200ms, deploy < 15min)"],["No tradeoffs acknowledged","Explicit what we WON\u2019T do"],["Roadmap without context","Narrative that explains WHY this sequence"],["No measurable outcomes","Success criteria with OKRs"]]) + """<p><b>Strategy Execution:</b> A strategy without execution is a wish. At Staff+ level, you own the strategy AND drive its adoption. Patterns: (1) Find 1-2 early adopters who are excited -> build momentum -> expand. (2) Make it easy: create templates, scripts, documentation. (3) Measure adoption: track migration progress, show before/after metrics. (4) Be patient: org-wide change takes 6-18 months.</p><p><b>Staff+ insight:</b> At Amazon, "Have Backbone; Disagree and Commit" means you must argue for your strategy vigorously, but once a decision is made, commit fully. At Google, strategy documents go through "review-then-decide" with stakeholders. The worst outcome is a strategy that no one has read or disagrees with silently.</p>""",
  "codeBlock": "# Strategy document template\nstrategy_doc = {\n    \"title\": \"Improving Developer Productivity: Build System Strategy 2024-2025\",\n    \"context\": {\n        \"current_state\": \"Our monorepo build takes 45 minutes (median). 500+ engineers affected daily.\",\n        \"problems\": [\"Cache hit rate is 20% due to imprecise dependency tracking\",\n                     \"Remote build workers are single-region and often exhausted\"],\n        \"opportunities\": \"Bazel remote caching API maturing. New vendor offers multi-region cache.\"\n    },\n    \"principles\": [\n        \"Developer velocity over infrastructure purity\",\n        \"Default to remote caching, local as fallback\",\n        \"No build should take > 10 minutes\"\n    ],\n    \"vision\": \"By Q4, median build time < 5 minutes, cache hit rate > 80%, developer satisfaction NPS > 50\",\n    \"strategic_bets\": {\n        \"will_do\": [\"Migrate to Bazel remote caching\", \"Adopt vendor X multi-region cache\"],\n        \"wont_do\": [\"Rewrite build system\", \"Migrate from monorepo to multi-repo\"]\n    },\n    \"roadmap\": [\n        {\"phase\": \"Q2\", \"actions\": [\"POC vendor X cache with 1 team\", \"Instrument build times\"],\n         \"success\": \"Cache hit rate > 50% for pilot team\"},\n        {\"phase\": \"Q3\", \"actions\": [\"Roll out to 5 teams\", \"Optimize dependency tracking\"],\n         \"success\": \"Median build < 15 min for adopted teams\"},\n        {\"phase\": \"Q4\", \"actions\": [\"Org-wide rollout\", \"Deprecate legacy build system\"],\n         \"success\": \"Median build < 5 min org-wide\"}\n    ],\n    \"risks\": [\"Vendor X reliability unknown -> have fallback plan\",\n               \"Teams resist migration -> assign build champions\"]\n}\n\n# Strategy checklist\ndef evaluate_strategy(doc):\n    checks = [\n        (\"Clear problem diagnosis\", len(doc.get(\"context\",{}).get(\"problems\",[])) > 0),\n        (\"Testable principles\", any(\"will\" in p.lower() for p in doc.get(\"principles\",[]))),\n        (\"Measurable vision\", \"NPS\" in doc.get(\"vision\",\"\") or \"percent\" in doc.get(\"vision\",\"\")),\n        (\"Tradeoffs explicit\", len(doc.get(\"strategic_bets\",{}).get(\"wont_do\",[])) > 0),\n        (\"Risks identified\", len(doc.get(\"risks\",[])) > 0),\n    ]\n    return sum(1 for _, ok in checks if ok), len(checks)"
})

S.append({
  "title": "3. Architecture Decision Records (ADRs)",
  "description": bd("ADR · DECISIONS · DOCUMENTATION · TEMPLATES", "#E95420") + """<p><b>Staff+ expectation:</b> ADRs capture the context and consequences of architectural decisions. At Staff+ level, you drive the ADR culture: "why did we choose X?" is documented so future engineers (and future you) can understand the reasoning.</p><p><b>ADR Format (Michael Nygard, 2011):</b></p><ol><li><b>Title:</b> Short noun phrase (0001-adopt-bazel-remote-caching.md)</li><li><b>Status:</b> Proposed, Accepted, Deprecated, Superseded</li><li><b>Context:</b> What is the problem? What constraints exist? What is the current situation?</li><li><b>Decision:</b> What did we decide? Be specific and unambiguous.</li><li><b>Consequences:</b> What becomes easier, harder, or impossible after this decision?</li><li><b>Options considered:</b> Alternatives with rationale for rejection (fairness to advocates, prevents re-litigation).</li></ol>""" + mg([("50-100","ADRs per year at a typical FAANG org","#E95420"),("2x","Faster onboarding with ADR culture","#E95420"),("~80%","Of ADR outcomes predicted correctly by senior engineers","#E95420")]) + """<p><b>ADR Anti-Patterns:</b> (1) Too long: keep ADRs under 1 page. If more detail is needed, link to a design doc. (2) No options considered: this creates re-litigation. (3) Status not updated: stale ADRs confuse. Assign an owner to keep ADRs current. (4) Everyone must approve: ADR is a record, not a consensus document. The decision-maker signs off, others are consulted.</p><p><b>Staff+ insight:</b> ADRs are not for every decision. Use for: decisions with long-term consequences (framework choice, data model, infrastructure), decisions that were contentious, decisions that multiple teams need to understand. Don\u2019t ADR: trivial implementation details, decisions easily reversed, personal preferences.</p>""",
  "codeBlock": "# ADR template\nadr_template = {\n    \"title\": \"ADR-0001: Adopt Bazel Remote Caching\",\n    \"status\": \"Accepted\",  # Proposed | Accepted | Deprecated | Superseded\n    \"date\": \"2024-03-15\",\n    \"deciders\": [\"Jane Doe (Staff)\", \"John Smith (Sr)\"],\n    \"context\": (\n        \"Our monorepo build takes 45 minutes median. Cache hit rate is 20%.\"\n        \" Local builds are CPU-bound and IO-bound. Engineers spend ~30% of their\"\n        \" day waiting for builds. Remote caching can share build artifacts across\"\n        \" all engineers and CI machines.\"\n    ),\n    \"decision\": (\n        \"Adopt Bazel remote caching via vendor X\u2019s multi-region cache service.\"\n        \" All CI builds publish artifacts. Developer builds check cache before\"\n        \" building locally. Cache key = hash of all inputs (source, config, toolchain).\"\n    ),\n    \"consequences\": {\n        \"positive\": [\n            \"Reduced median build time from 45min to < 5min\",\n            \"Cache hit rate expected > 80%\",\n            \"CI minutes reduced by 60%\"\n        ],\n        \"negative\": [\n            \"Vendor dependency for build infrastructure\",\n            \"Cache invalidation complexity for generated code\",\n            \"Cold cache after dependency upgrades\"\n        ]\n    },\n    \"options_considered\": [\n        {\"option\": \"Do nothing\", \"reason_rejected\": \"Build times are unacceptable\"},\n        {\"option\": \"Self-host remote cache\", \"reason_rejected\": \"Operational overhead, single-region\"},\n        {\"option\": \"Migrate to Buck (Meta)\", \"reason_rejected\": \"Larger migration scope, less community support\"}\n    ]\n}\n\n# ADR index\nclass ADRRegistry:\n    def __init__(self):\n        self.adrs = {}  # seq -> adr dict\n        self.next_seq = 1\n\n    def propose(self, adr):\n        seq = self.next_seq\n        adr[\"seq\"] = seq\n        adr[\"status\"] = \"Proposed\"\n        self.adrs[seq] = adr\n        self.next_seq += 1\n        return seq\n\n    def accept(self, seq):\n        if seq in self.adrs: self.adrs[seq][\"status\"] = \"Accepted\"\n\n    def supersede(self, old_seq, new_adr):\n        if old_seq in self.adrs:\n            self.adrs[old_seq][\"status\"] = \"Superseded\"\n            self.adrs[old_seq][\"superseded_by\"] = self.next_seq\n        return self.propose(new_adr)"
})

S.append({
  "title": "4. Design Doc Reviews: Running Effective Reviews at Scale",
  "description": bd("DESIGN DOCS · REVIEWS · FEEDBACK · COLLABORATION", "#4285F4") + """<p><b>Staff+ expectation:</b> Design doc reviews are the primary mechanism for technical alignment at FAANG. At Staff+ level, you write design docs that set technical direction and run review processes that produce better designs, not just rubber-stamped approvals.</p><p><b>When to Write a Design Doc:</b> (1) Significant architectural change (new service, data model change, infrastructure migration). (2) Cross-team impact (affects multiple teams\u2019 APIs, data, or workflows). (3) High risk (security, compliance, data loss potential). (4) Controversial (team disagrees on approach). Rule: if in doubt, write a 1-pager. It\u2019s cheaper than re-architecting after implementation.</p><p><b>Design Doc Structure (Google\u2019s Template):</b> Objective (1-2 sentences) -> Background/Context -> Goals + Non-Goals -> System Overview (architecture diagram) -> Detailed Design (APIs, data model, algorithms, storage) -> Alternatives Considered (at least 2) -> Operational Excellence (monitoring, deployment, rollback, failure modes) -> Security/Privacy Considerations -> Open Questions.</p>""" + tb(["Phase","Action","Time","Goal"],[["Socialization","Share draft with 2-3 trusted reviewers","2-3 days","Catch major issues before wider review"],["Review","Schedule review meeting or async review","1 week","Feedback from all stakeholders"],["Resolution","Author addresses feedback, decides on each","3-5 days","Update doc, note decisions"],["Approval","Tech lead / Staff engineer approves","1 day","Sign off or request changes"],["Implementation","Team implements, referencing design doc","Sprints","Build matches design"]]) + """<p><b>Staff+ insight on running reviews:</b> (1) Async review (comments in doc) is preferred for detailed feedback. Sync meeting is for resolving disagreements. (2) Time-box: max 2 weeks from draft to approval. After that, diminishing returns. (3) The author owns the decision, not the reviewers. Reviewers advise, author decides. (4) "Strong opinions, weakly held": advocate for your position but remain open to better arguments. (5) Document final decisions and rejected alternatives \u2014 prevents re-litigation.</p>""",
  "codeBlock": "# Design doc review workflow\nfrom enum import Enum\nimport time\n\nclass ReviewStatus(Enum):\n    DRAFT = 0\n    SOCIALIZING = 1\n    IN_REVIEW = 2\n    APPROVED = 3\n    REJECTED = 4\n\nclass ReviewComment:\n    def __init__(self, author, section, comment, severity=\"question\"):\n        self.author = author; self.section = section\n        self.comment = comment; self.severity = severity  # blocking | concern | question | nit\n        self.resolved = False; self.response = None\n\n    def resolve(self, response):\n        self.resolved = True; self.response = response\n\nclass DesignDoc:\n    def __init__(self, title, author, reviewers):\n        self.title = title; self.author = author\n        self.reviewers = reviewers\n        self.status = ReviewStatus.DRAFT\n        self.comments = []\n        self.decisions = []  # [(decision, rationale), ...]\n        self.created = time.time()\n\n    def add_comment(self, comment):\n        self.comments.append(comment)\n\n    def blocking_comments(self):\n        return [c for c in self.comments\n                if c.severity == \"blocking\" and not c.resolved]\n\n    def can_approve(self):\n        return self.status in (ReviewStatus.IN_REVIEW, ReviewStatus.APPROVED) \\\n            and len(self.blocking_comments()) == 0\n\n    def approve(self, reviewer):\n        if reviewer in self.reviewers and self.can_approve():\n            self.status = ReviewStatus.APPROVED\n            return True\n        return False\n\n# Quick 1-pager template\nquick_doc = {\n    \"problem\": \"What problem are we solving? (1 sentence)\",\n    \"proposal\": \"What do we propose to do? (2-3 sentences)\",\n    \"alternatives\": \"What else did we consider? (1 sentence each)\",\n    \"risks\": \"What could go wrong? (bullet list)\",\n    \"decision_needed\": \"What decision do we need from the reader?\"\n}"
})

S.append({
  "title": "5. Decision-Making Frameworks: CIRCLES, RICE, DACI & More",
  "description": bd("DECISIONS · FRAMEWORKS · TRADE-OFFS · STAFF+ TOOLS", "#FF6600") + """<p><b>Staff+ expectation:</b> Staff+ engineers make decisions that affect many people and persist for years. Using a framework ensures consistency, surfaces tradeoffs, and creates a record for future reference. Different frameworks for different decisions.</p>""" + tb(["Framework","Best for","Key elements","FAANG use"],[["CIRCLES","System design","Comprehend, Identify, Requirements, Core, Layers, Evaluations, Summary","Google interviews"],["RICE","Prioritization","Reach, Impact, Confidence, Effort","Product teams"],["DACI","Decision roles","Driver, Approver, Contributors, Informed","Any org decision"],["SPADE","Complex decisions","Setting, People, Alternatives, Decide, Explain","Amazon"],["OODA Loop","Fast decisions","Observe, Orient, Decide, Act","Military, Meta"]]) + """<p><b>DACI \u2014 The Decision-Making Role Framework:</b> <b>Driver</b> (1 person): drives the process, gathers input, proposes the decision. <b>Approver</b> (1 person): makes the final call. <b>Contributors</b> (2-5 people): provide input, expertise, and perspective. <b>Informed</b> (everyone else): notified of the outcome. Without DACI, either too many people try to decide (consensus gridlock) or no one knows who decided.</p><p><b>RICE \u2014 Prioritization:</b> Score = (Reach * Impact * Confidence) / Effort. <b>Reach:</b> how many users/teams affected per quarter. <b>Impact:</b> magnitude (0.25x minimalist to 3x massive). <b>Confidence:</b> how sure are we? (< 50% low, 80% medium, 100% high). <b>Effort:</b> person-months. At Google, RICE scores are used in OKR planning to decide "what do we do next quarter?"</p>""",
  "codeBlock": "# RICE prioritization calculator\nfrom dataclasses import dataclass\n\nclass RICE:\n    def __init__(self, name, reach, impact, confidence, effort):\n        self.name = name\n        self.reach = reach  # users/teams per quarter\n        self.impact = impact  # 0.25 (minimal) to 3 (massive)\n        self.confidence = confidence  # 0.0 to 1.0\n        self.effort = effort  # person-months\n\n    def score(self):\n        return (self.reach * self.impact * self.confidence) / self.effort\n\n    def __repr__(self):\n        return f\"RICE({self.name}: {self.score():.1f})\"\n\n# DACI role assignment\n@dataclass\nclass DACIDecision:\n    title: str\n    driver: str      # 1 person who drives the process\n    approver: str    # 1 person who makes the final call\n    contributors: list  # 2-5 people who provide input\n    informed: list   # everyone else who needs to know\n\n    def validate(self):\n        errors = []\n        if not self.driver: errors.append(\"Driver is required\")\n        if not self.approver: errors.append(\"Approver is required\")\n        if len(self.contributors) < 1: errors.append(\"At least 1 contributor\")\n        if self.driver == self.approver:\n            errors.append(\"Driver and Approver should be different\")\n        return errors\n\n# CIRCLES for system design\ndef circles_decision(context):\n    return {\n        \"comprehend\": \"What is the real question?\",\n        \"identify\": \"What kind of system? (read-heavy, write-heavy, real-time, batch)\",\n        \"requirements\": \"Functional + Non-functional with quantified targets\",\n        \"core_design\": \"Architecture diagram with components and data flow\",\n        \"layers\": \"Deep dive into 2-3 most interesting components\",\n        \"evaluations\": \"Tradeoffs: what did we NOT choose? What fails?\",\n        \"summary\": \"Recap decisions and open questions\"\n    }\n\n# Decision log\nclass DecisionLog:\n    def __init__(self):\n        self.decisions = []\n\n    def record(self, title, framework, outcome, rationale, participants):\n        self.decisions.append({\n            \"title\": title, \"framework\": framework,\n            \"outcome\": outcome, \"rationale\": rationale,\n            \"participants\": participants,\n            \"date\": __import__(\"time\").time()\n        })\n\n    def find(self, title):\n        return [d for d in self.decisions if title.lower() in d[\"title\"].lower()]"
})

S.append({
  "title": "6. Stakeholder Management & Cross-Team Collaboration",
  "description": bd("STAKEHOLDERS · ALIGNMENT · COMMUNICATION · INFLUENCE", "#E95420") + """<p><b>Staff+ expectation:</b> Technical work is only 50% of the Staff+ job. The other 50% is managing stakeholders, building alignment, and navigating organizational dynamics. A brilliant design that no one adopts is worse than a mediocre design that everyone uses.</p><p><b>Stakeholder Mapping:</b> Identify who cares about your work. Categories: (1) <b>Decision-makers</b> \u2014 the person who approves or blocks. (2) <b>Influencers</b> \u2014 respected engineers whose opinion shapes others. (3) <b>Implementers</b> \u2014 the teams who will build and operate the system. (4) <b>Consumers</b> \u2014 teams whose work depends on yours. (5) <b>Opponents</b> \u2014 people who may resist for legitimate reasons.</p>""" + tb(["Stakeholder Type","Engage how?","When?","Goal"],[["Decision-maker","1:1 meeting, exec summary","Before design review","Buy-in, remove blockers"],["Influencer","Tech design review, pair on POC","During design","Technical endorsement"],["Implementer","Design doc, RFC, walkthrough","Before implementation","Ownership, understanding"],["Consumer","API review, contract testing","During implementation","Compatibility assurance"],["Opponent","Understand concerns, find common ground","Ongoing","Surface hidden risks, find compromise"]]) + """<p><b>Cross-Team Collaboration Patterns:</b> (1) <b>Request for Comments (RFC):</b> Publish a design doc, collect async feedback from affected teams before implementation. Common at Meta. (2) <b>Working group:</b> Form a temporary group of representatives from affected teams to align on cross-cutting changes. (3) <b>API review board:</b> Regular meeting where API changes are reviewed for consistency and compatibility. (4) <b>Migration guild:</b> Cross-team group that coordinates large migrations (e.g., Bazel migration, Python 3 upgrade).</p><p><b>Staff+ insight:</b> The most common Staff+ failure is focusing entirely on technical excellence while ignoring organizational alignment. Your design is only as good as its adoption. Invest 30% of your time in stakeholder communication, not 10%.</p>""",
  "codeBlock": "# Stakeholder mapping template\nclass StakeholderMap:\n    def __init__(self):\n        self.stakeholders = {}  # name -> {role, influence, interest, engagement}\n\n    def add(self, name, role, influence=5, interest=5):\n        self.stakeholders[name] = {\n            \"role\": role,\n            \"influence\": influence,  # 1-10\n            \"interest\": interest,    # 1-10\n            \"engagement\": \"\",\n            \"concerns\": []\n        }\n\n    def prioritize(self):\n        # High influence + high interest = manage closely\n        # High influence + low interest = keep satisfied\n        # Low influence + high interest = keep informed\n        # Low influence + low interest = monitor\n        categories = {\"manage\": [], \"satisfy\": [], \"inform\": [], \"monitor\": []}\n        for name, s in self.stakeholders.items():\n            if s[\"influence\"] >= 7 and s[\"interest\"] >= 7:\n                categories[\"manage\"].append(name)\n            elif s[\"influence\"] >= 7:\n                categories[\"satisfy\"].append(name)\n            elif s[\"interest\"] >= 7:\n                categories[\"inform\"].append(name)\n            else:\n                categories[\"monitor\"].append(name)\n        return categories\n\n    def communication_plan(self):\n        plans = []\n        for name, s in self.stakeholders.items():\n            if s[\"influence\"] >= 7:\n                plans.append({\"name\": name, \"freq\": \"weekly 1:1\", \"format\": \"briefing\"})\n            elif s[\"interest\"] >= 7:\n                plans.append({\"name\": name, \"freq\": \"biweekly\", \"format\": \"email update\"})\n        return plans\n\n# Meeting facilitation: decision-forcing\nclass MeetingFacilitator:\n    @staticmethod\n    def decision_forcing(context, options, criteria):\n        \"\"\"Force a decision by scoring options against criteria.\"\"\"\n        scores = []\n        for opt_name, opt in options.items():\n            score = sum(criteria[c] * opt.get(c, 0) for c in criteria)\n            scores.append((score, opt_name))\n        scores.sort(reverse=True)\n        return scores"
})

S.append({
  "title": "7. Technical Debt Management: Strategy, Triage & Repayment",
  "description": bd("TECH DEBT · STRATEGY · TRIAGE · REFACTORING", "#4285F4") + """<p><b>Staff+ expectation:</b> Technical debt is inevitable. The Staff+ skill is managing it strategically, not eliminating it entirely. Some debt is an investment (speed now, pay later). Some debt is toxic (unmaintainable, blocking all progress). The Staff+ engineer can tell the difference.</p><p><b>Technical Debt Quadrant (Martin Fowler):</b></p>""" + tb(["","Reckless","Prudent"],[["Deliberate","We don\u2019t have time for design, ship now","We\u2019ll take on debt for speed, refactor in Q3"],["Inadvertent","We didn\u2019t know about better patterns (now we do)","We learn as we go, refactor when we understand the domain"]]) + """<p><b>Debt Triage Framework:</b> Evaluate each debt item on: (1) <b>Impact severity</b>: blocking feature work? causing outages? slowing development? (2) <b>Repayment cost</b>: person-weeks to fix? (3) <b>Risk of inaction</b>: how bad does it get if we wait? Prioritize: high severity + low cost = fix now (easy wins). High severity + high cost = plan and schedule. Low severity + low cost = fix opportunistically (boy scout rule). Low severity + high cost = accept as cost of business.</p><p><b>Refactoring Strategies:</b> (1) <b>Strangler Fig</b> (gradual replacement): build new system alongside old, route traffic incrementally. (2) <b>Bubble context</b> (isolate mess): wrap bad code behind an interface, refactor behind the facade. (3) <b>Big Bang</b> (total rewrite): almost always a mistake. Only justified when: current system is unmaintanable AND domain is well-understood AND you have 2x the time you estimate.</p>""",
  "codeBlock": "# Technical debt tracker\nfrom dataclasses import dataclass\nfrom enum import Enum\n\nclass Severity(Enum): LOW=0; MEDIUM=1; HIGH=2; CRITICAL=3\n\n@dataclass\nclass DebtItem:\n    title: str\n    description: str\n    severity: Severity\n    cost_weeks: float  # estimated person-weeks to fix\n    location: str  # file, service, area\n    tags: list = None\n\nclass DebtRegister:\n    def __init__(self):\n        self.items = []\n\n    def add(self, item):\n        self.items.append(item)\n\n    def prioritize(self):\n        scored = []\n        for item in self.items:\n            urgency = item.severity.value * 10 - item.cost_weeks\n            scored.append((urgency, item))\n        scored.sort(reverse=True)\n        return [item for _, item in scored]\n\n    def write_down(self, name, cost_weeks, reason):\n        \"\"\"Intentional debt: document why you\u2019re taking it on.\"\"\"\n        self.items.append(DebtItem(\n            title=name,\n            description=f\"Intentional: {reason}\",\n            severity=Severity.MEDIUM,\n            cost_weeks=cost_weeks,\n            location=\"\",\n            tags=[\"intentional\"]\n        ))\n\n    def total_cost(self):\n        return sum(i.cost_weeks for i in self.items)\n\n    def report(self):\n        return {\n            \"total_items\": len(self.items),\n            \"total_cost_weeks\": self.total_cost(),\n            \"by_severity\": {sev: len([i for i in self.items if i.severity == sev])\n                            for sev in Severity},\n            \"critical_items\": [i for i in self.items if i.severity == Severity.CRITICAL]\n        }\n\n# Boy scout rule: always leave the code a little cleaner than you found it\nclass BoyScoutRefactor:\n    @staticmethod\n    def apply(file_path):\n        return {\"action\": \"Rename unclear variables, extract 1 function, add 1 test\"}"
})

S.append({
  "title": "8. Build vs Buy: Decision Framework for Technical Leaders",
  "description": bd("BUILD VS BUY · MAKE VS BUY · PROCUREMENT · VENDOR", "#FF6600") + """<p><b>Staff+ expectation:</b> Build vs buy decisions are some of the highest-leverage decisions a Staff+ engineer makes. Choosing wrong can cost millions and waste years. At FAANG, the default is usually "build" for core differentiators and "buy" for commodity capabilities.</p><p><b>Decision Framework:</b></p><ul><li><b>Core differentiator?</b> If it\u2019s what makes your company unique (Google\u2019s search index, Amazon\u2019s recommendation engine), build it. Vendors can\u2019t differentiate for you.</li><li><b>Commodity capability?</b> If it\u2019s a solved problem (logging, monitoring, CI/CD), buy it. Your build version won\u2019t be better than a vendor whose entire business is that capability.</li><li><b>Integration surface?</b> If it needs deep integration with your core systems, building may be cheaper than adapting a vendor product.</li><li><b>Long-term cost?</b> Build: upfront cost + ongoing maintenance. Buy: subscription + switching cost. Total cost of ownership over 3-5 years.</li></ul>""" + tb(["Factor","Build when...","Buy when..."],[["Differentiation","Core to your competitive advantage","Commodity / table stakes"],["Talent","You have in-house expertise","No internal expertise, hard to hire"],["Time","You have 6-12 months","You need it in < 3 months"],["Total cost","One-time cost < 3yr subscription","3yr subscription < build maintenance"],["Integration","Deep integration needed","Standard API enough"],["Maintenance","You have team to maintain it","You don\u2019t want to own the ops"]]) + """<p><b>FAANG Build vs Buy Examples:</b> Google builds everything core (search, ads, storage, compute), buys for commodity (Slack, Jira, GitHub). Amazon builds (AWS, recommendation, fulfillment), buys for non-core. Meta builds (social graph, feed, ads), buys selectively (Workplace, Oculus acquisitions). Netflix builds (Open Connect CDN, Chaos Monkey, recommendation), buys (AWS compute, most SaaS).</p><p><b>Staff+ insight:</b> The biggest build vs buy mistakes come from not considering <b>total cost of ownership (TCO)</b>. Building a logging platform internally costs 2-3x the vendor subscription when you factor in pager duty, on-call rotations, feature requests, and migration costs. Conversely, buying your core differentiator gives your advantage to a vendor who can raise prices or go out of business.</p>""",
  "codeBlock": "# Build vs buy decision calculator\nfrom dataclasses import dataclass\n\n@dataclass\nclass BuildBuyAnalysis:\n    name: str\n    is_core_differentiator: bool\n    has_expertise: bool  # 1-10\n    time_available_months: int\n    build_cost_one_time: float  # person-months\n    build_annual_maintenance: float  # person-months/yr\n    buy_annual_subscription: float  # $\n    buy_implementation_months: float  # person-months\n    integration_complexity: int  # 1-10\n    vendor_risk: str  # low, medium, high\n\n    def recommend(self):\n        if self.is_core_differentiator:\n            return \"BUILD\", \"Core differentiator - must own\"\n        if self.time_available_months < 3 and not self.has_expertise:\n            return \"BUY\", \"No time to build, no expertise\"\n        build_3yr = self.build_cost_one_time + self.build_annual_maintenance * 3\n        buy_3yr = self.buy_annual_subscription * 3 + self.buy_implementation_months\n        if build_3yr * 10000 < buy_3yr:  # rough $/person-month\n            return \"BUILD\", f\"Cheaper over 3yr (build: {build_3yr:.0f} units vs buy: {buy_3yr:.0f})\"\n        return \"BUY\", f\"Cheaper over 3yr (buy: {buy_3yr:.0f} units vs build: {build_3yr:.0f})\"\n\n    def tco_report(self):\n        build = self.build_cost_one_time + self.build_annual_maintenance * 3\n        buy = self.buy_annual_subscription * 3 + self.buy_implementation_months\n        return {\n            \"build_3yr_tco\": f\"{build:.0f} person-months\",\n            \"buy_3yr_tco\": f\"{buy:.0f} person-months + ${self.buy_annual_subscription*3:.0f}\",\n            \"integration\": f\"{self.integration_complexity}/10 complexity\",\n            \"vendor_risk\": self.vendor_risk,\n            \"recommendation\": self.recommend()\n        }\n\n# Example: build a logging platform vs use Datadog\ndecision = BuildBuyAnalysis(\n    name=\"Logging Platform\",\n    is_core_differentiator=False,\n    has_expertise=True,  # we have infra engineers\n    time_available_months=6,\n    build_cost_one_time=24,  # 24 person-months\n    build_annual_maintenance=12,  # 12 person-months/yr\n    buy_annual_subscription=500000,  # $500K/yr\n    buy_implementation_months=2,\n    integration_complexity=3,\n    vendor_risk=\"low\"\n)\nprint(f\"Recommendation: {decision.recommend()}\")"
})

S.append({
  "title": "9. Mentorship, Sponsorship & Growing Senior Engineers",
  "description": bd("MENTORSHIP · SPONSORSHIP · TALENT · GROWTH", "#E95420") + """<p><b>Staff+ expectation:</b> At Staff+ level, your impact through others is as important as your direct technical contributions. You are assessed on how well you develop senior engineers, grow the next generation of leaders, and create a culture of technical excellence.</p><p><b>Mentorship vs Sponsorship:</b> Mentorship is advice and guidance ("I\u2019ll help you navigate this situation"). Sponsorship is advocacy and opportunity ("I\u2019ll recommend you for this promotion/stretch assignment/visible project"). At Staff+ level, sponsorship is more impactful. A sponsor puts their reputation on the line for you.</p>""" + tb(["Behavior","Mentorship","Sponsorship"],[["What","Gives advice, shares experience","Opens doors, creates opportunities"],["Audience","Anyone who asks","High-potential engineers you believe in"],["Cost","Time (low risk)","Reputation (high risk)"],["Impact","Guidance, skill building","Career acceleration, promotion"],["How","Regular 1:1s, feedback","Nominations, public advocacy, stretch assignments"]]) + """<p><b>Growing Senior Engineers to Staff:</b> Common blockers: (1) <b>Scope too narrow</b> \u2014 give cross-team projects that require coordination. (2) <b>No visibility</b> \u2014 ensure their work is seen by leadership (present at review, write strategy docs). (3) <b>No sponsorship</b> \u2014 actively advocate in promotion committees. (4) <b>No failure tolerance</b> \u2014 create safe spaces to take risks. At Amazon, the "bar raiser" program ensures engineers are pushed beyond their comfort zone during interviews; the same principle applies to growth.</p><p><b>Staff+ insight:</b> The best Staff+ engineers are known for how many other Staff+ engineers they developed, not just their own achievements. Track your "sponsorship portfolio": who have you sponsored in the last 2 years? What happened to them? If the answer is "no one," you\u2019re not doing the sponsorship part of the Staff+ role.</p>""",
  "codeBlock": "# Sponsorship tracking\nclass SponsorshipPortfolio:\n    def __init__(self):\n        self.sponsees = []\n\n    def sponsor(self, name, current_level, target_level, strengths, growth_areas):\n        self.sponsees.append({\n            \"name\": name,\n            \"current_level\": current_level,\n            \"target_level\": target_level,\n            \"strengths\": strengths,\n            \"growth_areas\": growth_areas,\n            \"started\": __import__(\"time\").time(),\n            \"outcomes\": []\n        })\n\n    def record_outcome(self, name, outcome):\n        for s in self.sponsees:\n            if s[\"name\"] == name:\n                s[\"outcomes\"].append(outcome)\n\n    def impact_report(self):\n        promoted = [s for s in self.sponsees\n                    if any(\"promoted\" in o.lower() for o in s[\"outcomes\"])]\n        return {\n            \"total_sponsored\": len(self.sponsees),\n            \"promotions\": len(promoted),\n            \"promotion_rate\": len(promoted) / max(len(self.sponsees), 1) * 100\n        }\n\n# Growth path: Senior -> Staff\ndef staff_growth_plan(engineer):\n    return {\n        \"current\": \"Senior Engineer (L5)\",\n        \"target\": \"Staff Engineer (L6)\",\n        \"timeline\": \"18-24 months\",\n        \"areas\": [\n            {\"skill\": \"Cross-team influence\", \"action\": \"Lead 1 cross-team project per quarter\",\n             \"evidence\": \"Design doc reviewed by 3+ teams\"},\n            {\"skill\": \"Technical decision-making\", \"action\": \"Own design decisions for your area\",\n             \"evidence\": \"ADR with your name as decider\"},\n            {\"skill\": \"Mentorship\", \"action\": \"Sponsor 2 junior engineers\",\n             \"evidence\": \"Promotion of 1 mentee\"},\n            {\"skill\": \"Communication\", \"action\": \"Present at internal conference or write strategy doc\",\n             \"evidence\": \"Presentation to director+ audience\"}\n        ]\n    }"
})

S.append({
  "title": "10. Leading Without Authority: Influence Patterns at FAANG",
  "description": bd("INFLUENCE · AUTHORITY · LEADERSHIP · ALIGNMENT", "#4285F4") + """<p><b>Staff+ expectation:</b> Staff+ engineers rarely have direct reports. You lead through influence, not authority. This is the hardest skill to learn and the most important for Staff+ success.</p><p><b>Influence Patterns (Cialdini\u2019s Principles Applied to Engineering):</b></p><ul><li><b>Reciprocity:</b> Help others first (code reviews, debugging, design feedback). When you need something, people remember. At Google, the most influential engineers are also the most helpful.</li><li><b>Social Proof:</b> Get early adopters -> create momentum -> others follow. A migration with 2 teams already on board is much easier to sell than one starting from zero.</li><li><b>Authority:</b> Build your expertise reputation. Write design docs, speak at internal conferences, be the person who answers hard questions. Authority is earned, not granted.</li><li><b>Liking:</b> Invest in relationships before you need them. Grab coffee, learn about people\u2019s interests, be genuinely helpful. People say yes to people they like.</li><li><b>Scarcity:</b> Frame your proposal around limited opportunities. "We have a 3-month window to migrate before the API is deprecated." Urgency drives action.</li><li><b>Commitment:</b> Start small. Get a shared understanding on 1 principle -> then 2 -> then the whole strategy. Consistent small commitments build to large alignment.</li></ul>""" + tb(["Pattern","How it works","Engineering example"],[["Reciprocity","Give -> receive","Review their design doc first, then ask them to review yours"],["Social Proof","Early adopters attract more","Get 1 team to adopt your migration plan, show results to others"],["Authority","Expert reputation","Become the go-to person for a technology area"],["Liking","Personal connection","Build relationships before you need alignment"],["Scarcity","Limited opportunity frame","We have 6 months until the cloud contract renews"],["Commitment","Small -> large","Agree on 1 principle first -> build to full strategy"]]) + """<p><b>Staff+ insight:</b> The single most effective influence technique at FAANG is <b>making the right thing easy</b>. Create templates, scripts, automated migration tools, and clear documentation. If you want teams to adopt your API design pattern, provide a code generator. If you want teams to migrate to your build system, provide an automated migration script. Reduce the cost of saying yes to zero.</p>""",
  "codeBlock": "# Influence measurement (retrospective)\nclass InfluenceTracker:\n    def __init__(self):\n        self.initiatives = []  # {name, adopters, time_to_adoption, strategy}\n\n    def add_initiative(self, name, strategy, adopters_expected):\n        self.initiatives.append({\n            \"name\": name,\n            \"strategy\": strategy,  # which influence patterns used\n            \"adopters_expected\": adopters_expected,\n            \"adopters_actual\": 0,\n            \"started\": __import__(\"time\").time()\n        })\n\n    def record_adoption(self, name, team):\n        for i in self.initiatives:\n            if i[\"name\"] == name:\n                i[\"adopters_actual\"] += 1\n\n    def influence_score(self):\n        scores = []\n        for i in self.initiatives:\n            if i[\"adopters_expected\"] > 0:\n                ratio = i[\"adopters_actual\"] / i[\"adopters_expected\"]\n                scores.append({\"name\": i[\"name\"], \"adoption_ratio\": ratio,\n                               \"strategy\": i[\"strategy\"]})\n        return scores\n\n# Making the right thing easy: migration tool pattern\nclass AutomatedMigration:\n    def __init__(self, from_pattern, to_pattern):\n        self.from_pattern = from_pattern\n        self.to_pattern = to_pattern\n        self.codemod_rules = []  # ast-based transformation rules\n\n    def add_rule(self, description, match_fn, replace_fn):\n        self.codemod_rules.append({\"desc\": description,\n                                   \"match\": match_fn, \"replace\": replace_fn})\n\n    def dry_run(self, code):\n        changes = []\n        for rule in self.codemod_rules:\n            matches = rule[\"match\"](code)\n            for m in matches:\n                changes.append({\"rule\": rule[\"desc\"], \"location\": m})\n        return changes\n\n    def apply(self, code):\n        for rule in self.codemod_rules:\n            code = rule[\"replace\"](code)\n        return code"
})

S.append({
  "title": "11. Estimation & Planning: How Staff+ Engineers Plan Work",
  "description": bd("ESTIMATION · PLANNING · OKRS · ROADMAPPING", "#FF6600") + """<p><b>Staff+ expectation:</b> Estimation is not about predicting the future correctly \u2014 it\u2019s about creating shared understanding of uncertainty and building contingency. At Staff+ level, you own quarterly planning, OKR setting, and roadmap communication for your area.</p><p><b>Estimation Techniques:</b></p><ul><li><b>Reference class forecasting:</b> Instead of guessing from scratch, ask "how long did similar projects take?" At Google, historical project data shows most projects take 2-3x longer than initial estimates.</li><li><b>Three-point estimation:</b> Optimistic (O), Most Likely (M), Pessimistic (P). Expected = (O + 4M + P) / 6. This gives a probability distribution, not a single number.</li><li><b>Planning poker (teams):</b> Each team member privately estimates. Reveal. Discuss outliers. Repeat until converge. Surfaces hidden assumptions.</li><li><b>Bucket method (large scale):</b> Categorize tasks into size buckets (XS=1d, S=3d, M=1w, L=2w, XL=1m). Less precision, more consistency across teams.</li></ul>""" + tb(["Technique","Best for","Accuracy","Time cost"],[["Reference class","Large projects","Good (historical data)","Low (look up past projects)"],["Three-point","Medium projects","Fair (range)","Medium"],["Planning poker","Team sprint planning","Good (team consensus)","Medium (30-60 min)"],["Bucket method","Org-wide planning","Fair (categories)","Low (15 min per person)"],["No estimation","Small/simple tasks","N/A","Zero (just start)"]]) + """<p><b>OKR Setting for Engineering:</b> Objectives are qualitative and inspirational ("Delight users with instant search"). Key Results are quantitative and measurable ("p50 search latency < 10ms"). Good KRs are: specific, measurable, achievable, relevant, time-bound. At Google: OKRs are set quarterly, weighted (60% committed, 40% aspirational). A 70% completion rate is considered successful for aspirational OKRs.</p><p><b>Staff+ insight:</b> The most reliable estimator at FAANG is: take the engineering team\u2019s naive estimate, multiply by 2, then add 1 sprint for integration testing + 1 sprint for edge cases + 1 sprint for production rollout. This is not cynicism \u2014 it\u2019s experience. A project that "feels like 2 months" is actually 5-6 months. Plan accordingly.</p>""",
  "codeBlock": "# Estimation tools\nimport math\n\nclass ThreePointEstimate:\n    def __init__(self, optimistic, most_likely, pessimistic):\n        self.O = optimistic\n        self.M = most_likely\n        self.P = pessimistic\n\n    @property\n    def expected(self):\n        return (self.O + 4*self.M + self.P) / 6\n\n    @property\n    def std_dev(self):\n        return (self.P - self.O) / 6\n\n    def confidence(self, target_weeks):\n        \"\"\"Probability of completing within target weeks (normal approx).\"\"\"\n        z = (target_weeks - self.expected) / max(self.std_dev, 0.01)\n        return 0.5 * (1 + math.erf(z / math.sqrt(2)))\n\n    def weeks_for_confidence(self, pct):\n        z = {0.5: 0, 0.7: 0.52, 0.8: 0.84, 0.9: 1.28, 0.95: 1.65}[pct]\n        return self.expected + z * self.std_dev\n\n    def __repr__(self):\n        return f\"{self.expected:.1f} +/- {self.std_dev:.1f} weeks\"\n\n# Example: estimate a migration\nmigration = ThreePointEstimate(optimistic=4, most_likely=8, pessimistic=16)\nprint(f\"Expected: {migration.expected:.0f} weeks\")\nprint(f\"90% confidence: {migration.weeks_for_confidence(0.9):.0f} weeks\")\nprint(f\"Probability within 10 weeks: {migration.confidence(10)*100:.0f}%\")\n\n# OKR template\nclass OKR:\n    def __init__(self, objective, krs):\n        self.objective = objective\n        self.key_results = [{\"kr\": kr, \"target\": 100, \"actual\": 0} for kr in krs]\n        self.weight = 1.0  # 0.0 to 1.0\n\n    def update(self, kr_idx, actual):\n        if 0 <= kr_idx < len(self.key_results):\n            self.key_results[kr_idx][\"actual\"] = actual\n\n    def progress(self):\n        if not self.key_results: return 0\n        return sum(min(kr[\"actual\"] / max(kr[\"target\"], 1), 1)\n                   for kr in self.key_results) / len(self.key_results)\n\n    def is_on_track(self):\n        mid = __import__(\"time\").time() % (365*86400) / (365*86400)\n        return self.progress() >= mid * 0.8\n\n# Reference class forecasting\nclass ReferenceClass:\n    def __init__(self):\n        self.projects = []  # [(estimated_weeks, actual_weeks, complexity), ...]\n\n    def add_project(self, estimated, actual, complexity=\"medium\"):\n        self.projects.append((estimated, actual, complexity))\n\n    def multiplier(self):\n        if not self.projects: return 2.5\n        ratios = [a/e for e, a, _ in self.projects if e > 0]\n        return sum(ratios) / len(ratios)\n\n    def predict(self, naive_estimate):\n        return naive_estimate * self.multiplier()"
})

S.append({
  "title": "12. Incident Leadership: Being the Calm in the Storm",
  "description": bd("INCIDENT · LEADERSHIP · COMMS · CRISIS", "#E95420") + """<p><b>Staff+ expectation:</b> When a major incident happens, the Staff+ engineer is often the Incident Commander (IC). Your job is not to debug \u2014 it\u2019s to coordinate, communicate, and make decisions under pressure. The best ICs create space for SMEs to think while shielding them from chaos.</p><p><b>Incident Command Responsibilities:</b> (1) Triages incoming information, decides severity. (2) Assigns roles: Ops Lead, Comms Lead, Scribe. (3) Establishes communication cadence (every 15 min for SEV-1). (4) Makes time-critical decisions: rollback?, failover?, page more people? (5) Manages external communication: exec updates, customer-facing status page. (6) Drives to mitigation, not root cause (find root cause after service is restored).</p><p><b>Incident Command Mistakes:</b> (1) Debugging instead of coordinating (you have SMEs for that). (2) Not delegating \u2014 trying to do everything yourself. (3) Tunnel vision on one theory while ignoring other possibilities. (4) Poor communication \u2014 stakeholders get anxious when they don\u2019t hear anything. (5) Not calling it early enough \u2014 escalating late is worse than escalating early.</p>""" + tb(["Phase","IC actions","SME actions","Comms actions"],[["Detection","Confirm severity, declare incident","Start investigating","Notify stakeholders"],["Triage","Assign roles, set cadence","Isolate the problem","Status page update"],["Mitigation","Decide: rollback? failover?","Implement mitigation","15-min updates to exec"],["Resolution","Verify mitigated, monitor","Confirm fix works","Final status update"],["Postmortem","Schedule postmortem, assign owner","Document timeline","Share learning with org"]]) + """<p><b>Staff+ insight:</b> The mark of Staff+ incident leadership: when you walk into the war room, the team goes from panicked to focused. Not because you have the answers, but because you bring structure, clarity, and calm. After the incident, the team should feel "we handled that well together," not "the Staff engineer saved us." Your job is to enable the team, not to be the hero.</p>""",
  "codeBlock": ""
})

S.append({
  "title": "13. Engineering Culture: Building High-Trust, High-Performance Teams",
  "description": bd("CULTURE · TRUST · DEVOPS · BLAMELESS · EXCELLENCE", "#4285F4") + """<p><b>Staff+ expectation:</b> Culture is what happens when no one is watching. At Staff+ level, you don\u2019t just follow the culture \u2014 you shape it. Your behavior sets the standard for engineering excellence, collaboration, and operational maturity.</p><p><b>Elements of High-Performance Engineering Culture:</b></p><ul><li><b>Psychological safety:</b> Engineers can admit mistakes, ask dumb questions, and challenge ideas without fear of punishment. Google\u2019s Project Aristotle found this is the #1 predictor of team effectiveness.</li><li><b>Blameless postmortems:</b> Incidents are system failures, not human failures. The question is "what in the system allowed this to happen?" not "who made the mistake?"</li><li><b>Continuous improvement:</b> After every incident, release, or milestone, ask: what went well? what could be better? what will we change? Kaizen for engineering.</li><li><b>Engineering excellence:</b> Code review is non-negotiable. Testing is expected. Documentation is part of done. These aren\u2019t bureaucratic overhead \u2014 they\u2019re how you sustain velocity.</li><li><b>Open disagreement:</b> "Strong opinions, weakly held." Argue passionately for your position, but be ready to change your mind when better evidence appears. Disagree openly, then commit fully.</li></ul>""" + tb(["Culture attribute","Low-trust team","High-trust team"],[["Mistakes","Hidden, blamed","Shared, learned from"],["Disagreement","Silent, resentful","Open, constructive"],["Code review","Rubber stamp or gate","Learning opportunity"],["On-call","Feared, avoided","Shared ownership"],["Postmortems","Blame assignment","System improvement"],["Deployments","Risky events","Low-risk, frequent"],["Documentation","Outdated, ignored","Living, maintained"]]) + """<p><b>Staff+ culture-building actions:</b> (1) Model the behavior you want to see \u2014 admit your own mistakes publicly. (2) Celebrate good postmortems (the ones that find systemic issues, not the ones that blame). (3) Create rituals: weekly demo day, monthly tech talk, quarterly postmortem review. (4) Remove barriers: if code review is slow, fix the review process. If testing is hard, provide test infrastructure.</p><p><b>Staff+ insight:</b> Culture is built by what you <i>tolerate</i>, not just what you <i>celebrate</i>. If you tolerate blame in postmortems, you get fear. If you tolerate unreviewed code, you get technical debt. If you tolerate silent disagreements, you get resentment. Every time you see a behavior that undermines culture and say nothing, you\u2019re endorsing it.</p>""",
  "codeBlock": "# Culture health survey\nclass CultureSurvey:\n    DIMENSIONS = [\"psychological_safety\", \"blamelessness\", \"continuous_improvement\",\n                  \"engineering_excellence\", \"open_disagreement\"]\n\n    def __init__(self):\n        self.responses = []  # list of dicts: {dimension: score (1-5), comment: str}\n\n    def add_response(self, dimension, score, comment=\"\"):\n        self.responses.append({\"dimension\": dimension, \"score\": score, \"comment\": comment})\n\n    def dimension_avg(self, dimension):\n        scores = [r[\"score\"] for r in self.responses if r[\"dimension\"] == dimension]\n        return sum(scores) / len(scores) if scores else 0\n\n    def report(self):\n        return {d: self.dimension_avg(d) for d in self.DIMENSIONS}\n\n    def weakest(self):\n        return min(self.DIMENSIONS, key=lambda d: self.dimension_avg(d))\n\n# Team health check\nclass TeamHealthCheck:\n    @staticmethod\n    def evaluate(team):\n        checks = [\n            (\"Deploy frequency\", team.get(\"deploys_per_week\", 0) >= 5),\n            (\"Lead time\", team.get(\"lead_time_hours\", 999) < 24),\n            (\"MTTR\", team.get(\"mttr_minutes\", 999) < 60),\n            (\"Change failure rate\", team.get(\"change_failure_pct\", 100) < 15),\n            (\"Postmortem rate\", team.get(\"postmortems_per_quarter\", 0) >= 1),\n            (\"Code review coverage\", team.get(\"review_pct\", 0) >= 90),\n        ]\n        passed = sum(1 for _, ok in checks if ok)\n        return {\"checks\": checks, \"score\": f\"{passed}/{len(checks)}\",\n                \"elite\": passed >= 5, \"high\": passed >= 3}"
})

S.append({
  "title": "14. Writing & Communication: Engineering Prose That Moves People",
  "description": bd("WRITING · COMMUNICATION · DOCS · PRESENTATIONS", "#FF6600") + """<p><b>Staff+ expectation:</b> At Staff+ level, your writing is seen by dozens or hundreds of people. A poorly written design doc creates confusion, delays, and rework. A well-written one creates alignment and accelerates execution.</p><p><b>Principles of Engineering Writing (Google, Amazon):</b></p><ul><li><b>Know your audience.</b> Exec summary for directors. Technical detail for implementers. Both in the same doc? Use TL;DR with links to depth sections.</li><li><b>Start with the conclusion.</b> "We recommend adopting Bazel remote caching." Then explain why. Busy readers should know the key point in 5 seconds.</li><li><b>One idea per paragraph.</b> Topic sentence -> supporting detail -> transition. If you can\u2019t summarize a paragraph in 5 words, it has too many ideas.</li><li><b>Use lists and tables.</b> Walls of text are skipped. Compare alternatives in a table. List action items. Use bold for key terms.</li><li><b>Cut ruthlessly.</b> "I didn\u2019t have time to write a short letter, so I wrote a long one instead" \u2014 Mark Twain. Editing is a Staff+ skill. A 3-page design doc is almost always better than a 10-page one.</li></ul>""" + tb(["Bad writing signal","Fix","Why"],[["No TL;DR","Add 2-3 sentence summary","90% of readers won\u2019t read the full doc"],["Passive voice everywhere","Use active voice","We decided X (not, it was decided that X)"],["Abstract language","Concrete examples","An example is worth 100 words of abstraction"],["No headings","Use section headers","Readers skip to relevant sections"],["No alternatives","Mention what you rejected","Shows you considered options, prevents re-litigation"],["Too long","Cut 50%","Brevity is respect for the reader\u2019s time"]]) + """<p><b>Staff+ communication patterns:</b> (1) <b>Context first:</b> Before asking a question or making a request, provide enough context that the recipient can respond without asking "why?" (2) <b>Async by default:</b> Write before you talk. A well-written doc replaces 3 meetings. (3) <b>Decision-focused:</b> When you write, make it clear what decision you need from the reader. End with "I\u2019d like your approval on X by Friday." (4) <b>Status updates:</b> Brief, regular, structured. "What happened, what\u2019s next, what\u2019s blocked." No fluff.</p>""",
  "codeBlock": "# Writing quality checker\nclass WritingReview:\n    WEAK_WORDS = [\"might\", \"maybe\", \"possibly\", \"consider\", \"think about\",\n                  \"should\", \"could\", \"would\", \"seems\", \"appears\"]\n\n    @staticmethod\n    def check(text):\n        issues = []\n        words = text.lower().split()\n\n        for w in WritingReview.WEAK_WORDS:\n            if w in words:\n                issues.append(f\"Weak word: '{w}' - replace with stronger language\")\n\n        # Check for passive voice indicators\n        for match in [\"was \", \"were \", \"been \", \"being \"]:\n            if match in text.lower() and \" by \" in text.lower():\n                issues.append(f\"Passive voice detected near '{match}'\")\n\n        paragraphs = [p for p in text.split(\"\\n\") if p.strip()]\n        for p in paragraphs:\n            if len(p) > 500:\n                issues.append(f\"Paragraph too long ({len(p)} chars): split into multiple paragraphs\")\n\n        return {\"score\": max(0, 10 - len(issues)), \"issues\": issues}\n\n# TL;DR generator\ndef make_tldr(doc_text):\n    \"\"\"Extract first sentence of each section for a summary.\"\"\"\n    lines = doc_text.strip().split(\"\\n\")\n    key_points = []\n    for line in lines:\n        if line.startswith(\"## \") or line.startswith(\"### \"):\n            section = line.strip(\"# \").strip()\n        elif line.strip() and not line.startswith(\"#\"):\n            first_sentence = line.strip().split(\".\")[0]\n            if first_sentence and len(first_sentence) > 20:\n                key_points.append(f\"  - {first_sentence}.\")\n    return \"TL;DR:\\n\" + \"\\n\".join(key_points[:5])\n\n# Staff+ email template\ndef staff_email(subject, context, decision_needed, deadline):\n    return f\"\"\"Subject: {subject}\n\nContext: {context}\n\nDecision needed: {decision_needed}\n\nPlease respond by {deadline} or the default decision is X.\n\n(Motes: doc link with full analysis)\"\"\""
})

S.append({
  "title": "15. Career Navigation: Promotions, Job Changes & Personal Brand",
  "description": bd("CAREER · PROMOTION · BRAND · JOB CHANGE", "#4285F4") + """<p><b>Staff+ expectation:</b> Career growth at Staff+ level is not linear. Promotions are harder, take longer, and depend more on impact than effort. At FAANG, the gap between Staff and Senior Staff is larger than the gap between Junior and Senior.</p><p><b>Promotion to Staff (L6/L7 equivalent):</b> At Google/Facebook/Amazon, the Staff promotion requires: (1) Impact across multiple teams (not just your team). (2) Technical leadership that produced measurable business results. (3) Evidence of developing other engineers. (4) A strong promotion packet written by your manager with endorsements from cross-team peers. Timeline: typical time at Senior is 3-6 years before Staff promotion. Only ~30% of Senior engineers reach Staff.</p>""" + tb(["Level","Scope","Promotion criteria","Timeline"],[["Senior (L5)","Your team","Technical depth, delivery","3-6 years post-mid"],["Staff (L6)","Your org (2-5 teams)","Cross-team impact, strategy, mentorship","3-6 years post-senior"],["Senior Staff (L7)","Multiple orgs","Org-wide strategy, industry influence","3-5 years post-staff"],["Principal (L8)","Company","Industry recognition, company-wide architecture","Rare < 1% of engineers"]]) + """<p><b>Personal Brand for Staff+:</b> (1) Be known for something: you don\u2019t need to be known for everything, but you need to be the go-to person for <i>something</i>. (2) Write: blog posts, internal design docs, strategy documents. Writing scales. (3) Speak: internal tech talks, conferences, team all-hands. Visibility matters. (4) Build a network: cross-team relationships take time to build but pay off in influence. (5) Track your impact: keep a "brag doc" of achievements, numbers, and testimonials. You\u2019ll need it for promotion packets.</p><p><b>Staff+ insight:</b> The Staff+ promotion is not a reward for good work \u2014 it\u2019s a bet on future potential. Your promotion packet must convince the committee that you will continue to have cross-team impact at the next level. The most common reason for Staff promotion failure is insufficient evidence of <i>cross-team</i> impact, even when individual contributions are outstanding.</p>""",
  "codeBlock": "# Brag doc / promotion packet template\nclass BragDoc:\n    def __init__(self, name, current_level, target_level):\n        self.name = name\n        self.current_level = current_level\n        self.target_level = target_level\n        self.achievements = []  # {impact, team, metrics, date}\n        self.endorsements = []  # {name, role, quote}\n\n    def add_achievement(self, impact, team, metrics):\n        self.achievements.append({\n            \"impact\": impact,\n            \"team\": team,\n            \"metrics\": metrics,\n            \"date\": __import__(\"time\").time()\n        })\n\n    def add_endorsement(self, name, role, quote):\n        self.endorsements.append({\"name\": name, \"role\": role, \"quote\": quote})\n\n    def generate_packet(self):\n        return {\n            \"candidate\": {\"name\": self.name, \"from\": self.current_level,\n                          \"to\": self.target_level},\n            \"impact_summary\": f\"{len(self.achievements)} achievements across \"\n                              f\"{len(set(a['team'] for a in self.achievements))} teams\",\n            \"key_metrics\": [a[\"metrics\"] for a in self.achievements[:5]],\n            \"endorsements\": self.endorsements[:3]\n        }\n\n    def promotion_readiness(self):\n        cross_team = len(set(a[\"team\"] for a in self.achievements))\n        has_mentorship = any(\"mentor\" in a[\"impact\"].lower() or \"sponsor\" in a[\"impact\"].lower()\n                            for a in self.achievements)\n        return {\n            \"cross_team_impact\": f\"{cross_team} teams\",\n            \"mentorship_evidence\": has_mentorship,\n            \"endorsement_count\": len(self.endorsements),\n            \"ready\": cross_team >= 3 and has_mentorship and len(self.endorsements) >= 2\n        }\n\n# Promotion committee simulation\ndef promotion_committee(projected_impact, endorsements, brag_doc):\n    score = 0\n    score += 30 if projected_impact.get(\"cross_team\") else 0\n    score += 20 if projected_impact.get(\"org_wide\") else 10\n    score += 25 if len(endorsements) >= 3 else 0\n    score += 25 if brag_doc.promotion_readiness()[\"ready\"] else 0\n    result = \"Promote\" if score >= 70 else \"Not Yet\"\n    return {\"score\": score, \"result\": result, \"feedback\": []}"
})

S.append({
  "title": "16. Staff+ Engineering Patterns Interview Strategy",
  "description": bd("INTERVIEW · BEHAVIORAL · LEADERSHIP · STRATEGY", "#FF6600") + """<p><b>Staff+ expectation:</b> Unlike coding or system design interviews, Staff+ interviews focus on leadership, judgment, and experience. You\u2019ll face behavioral questions, hypothetical scenarios, and cross-functional discussions. At FAANG, these interviews are often the difference between Senior and Staff offers.</p><p><b>Common Staff+ Behavioral Questions:</b></p><ul><li>"Tell me about a time you influenced a team that didn\u2019t report to you." (Influence without authority)</li><li>"Describe a project where you had to make a technical decision with incomplete information." (Decision-making under uncertainty)</li><li>"Tell me about a time you led a cross-team initiative. What was the outcome?" (Cross-team collaboration)</li><li>"Describe a situation where you disagreed with your manager or a senior leader." (Courage / backbone)</li><li>"Tell me about the hardest technical problem you solved in the last year." (Technical depth + impact)</li><li>"How do you handle a situation where a team is resistant to a migration you\u2019re leading?" (Conflict resolution / influence)</li></ul><p><b>STAR Format for Staff+:</b> <b>Situation</b> \u2014 set context, scope, stakes. <b>Task</b> \u2014 what was your specific role? <b>Action</b> \u2014 what did you DO (not what the team did). <b>Result</b> \u2014 quantified impact. Staff+ difference: add <b>Learnings</b> \u2014 what would you do differently? The "learning" element is what separates Staff+ from Senior.</p>""" + tb(["Component","Example (weak)","Example (Staff+)"],[["Situation","We had a scalability problem","Our service served 10K QPS and was failing p99 latency targets of 200ms. We were losing $50K/day in revenue."],["Task","I was asked to fix it","I initiated and led a cross-team effort with infra, product, and SRE to redesign the caching layer."],["Action","We added caching","I analyzed traffic patterns, identified cache miss hotspots, proposed a multi-tier cache architecture, built consensus across 3 teams, and led the implementation."],["Result","Latency improved","p99 latency dropped from 2s to 50ms. CDN costs reduced by 40%. Revenue recovered. Postmortem published."],["Learning","We should do this earlier","I learned that stakeholder buy-in is as important as technical design. In hindsight, I\u2019d socialize the design earlier."]]) + """<p><b>Staff+ insight:</b> The most common mistake in Staff+ behavioral interviews is being too humble about your role. "We" is fine, but the interviewer needs to know what <i>you</i> specifically contributed. If you were the tech lead, say "I was the tech lead." If you made the key decision, say "I decided to use X because \u2026" Own your impact.</p>""",
  "codeBlock": "# Behavioral interview prep: STAR builder\ndef build_star(situation, task, action, result, learning=None):\n    return {\n        \"Situation\": situation,\n        \"Task\": task,\n        \"Action\": action,\n        \"Result\": result,\n        \"Learning (Staff+) \": learning or \"N/A\"\n    }\n\n# Example: Staff+ influence scenario\ndef influence_scenario():\n    scenario = build_star(\n        situation=\"Our team wanted to migrate from Jenkins to GitHub Actions. The infra team was resistant.\",\n        task=\"I needed to convince the infra team to support the migration without authority over their roadmap.\",\n        action=\"I built a POC showing 60% faster CI times with GHA. Shared results with infra in a 1:1. Offered to handle migration for the first 5 repos myself to reduce their risk.\",\n        result=\"Infra agreed to a trial. After 3 months, 10 teams adopted. CI wait times dropped 60%. Infra adopted GHA as the org standard.\",\n        learning=\"Go with a POC, not a proposal. Showing > telling. Give skeptics an easy way to say 'yes.' \"\n    )\n    return scenario\n\n# Interview prep: common Staff+ topics to prepare\ndef prep_topics():\n    return [\n        \"Cross-team technical leadership\",\n        \"Technical decision-making under uncertainty\",\n        \"Influence without authority\",\n        \"Conflict resolution\",\n        \"Strategic vs tactical tradeoffs\",\n        \"Mentorship and sponsorship examples\",\n        \"Incident leadership\",\n        \"Culture building\",\n        \"Communication and writing samples\"\n    ]\n\n# Staff+ prompts: questions to ask your interviewer\nstaff_ask_questions = [\n    \"How does the company define the Staff+ role and what are the expectations?\",\n    \"What is the biggest technical challenge the team is facing right now?\",\n    \"How does the team handle technical disagreements?\",\n    \"What opportunities exist for cross-team influence?\",\n    \"What does success look like for a Staff+ engineer in this org?\"\n]"
})

S.append({
  "title": "17. References & Further Reading",
  "description": tb(["Topic","Resource","Why for Staff+"],[["Staff+ Role","The Staff Engineer\u2019s Path (Tanya Reilly)","The definitive book on the Staff+ role, scope, and expectations"],["Staff+ Archetypes","StaffEng.com (staffeng.com)","Interviews with 50+ Staff+ engineers at FAANG"],["Influence","Influence: The Psychology of Persuasion (Cialdini)","The 6 principles of influence \u2014 essential for staff"],["Technical Strategy","Good Strategy Bad Strategy (Rumelt)","Diagnosis + guiding policy + coherent actions"],["Decisions","Thinking in Bets (Duke)","Decision-making under uncertainty"],["Writing","Writing for Engineers (Hilton)","How to write effective engineering documents"],["ADRs","ADR GitHub Organization (adr.github.io)","ADR templates, tools, and patterns"],["Design Docs","Google Design Doc Template (google.com)","The standard template used at Google"],["Culture","An Elegant Puzzle (Larson)","Systems thinking for engineering management"],["Mentorship","The Mentor\u2019s Guide (Zachary)","Becoming an effective mentor and sponsor"],["Promotions","Staff Engineer: Promotion Packets (staffeng.com)","How to write a promotion packet that works"],["Leadership","Turn the Ship Around (Marquet)","Leadership without authority \u2014 giving control to the team"]]),
  "codeBlock": ""
})

doc = {
  "id": "engineering-patterns-staff",
  "title": "Staff+ Engineering Patterns \u2014 FAANG Interview Prep",
  "category": "Engineering Patterns",
  "subcategory": "Staff+ Interview Prep",
  "description": "Comprehensive guide to the Staff+ engineer role at FAANG \u2014 the patterns, strategies, and mindsets that separate Staff+ engineers from Senior. Covers the Staff+ role & scope, technical strategy writing, ADRs, design doc reviews, decision-making frameworks (CIRCLES, RICE, DACI), stakeholder management & cross-team collaboration, technical debt strategy, build vs buy analysis, mentorship & sponsorship, leading without authority, estimation & planning, incident leadership, engineering culture, engineering writing, career navigation & promotions, and Staff+ behavioral interview strategy.",
  "language": "text",
  "codeBlock": "",
  "details": (
    '<p class="mb-3"><b>Staff+ FAANG Interview Strategy for Engineering Leadership:</b> Staff+ '
    'behavioral interviews test (1) <b>Influence without authority</b> \u2014 can you drive change '
    'without direct reports?, (2) <b>Technical decision-making</b> \u2014 how do you make tradeoffs '
    'under uncertainty?, (3) <b>Cross-team impact</b> \u2014 do you deliver results across org '
    'boundaries?, (4) <b>Mentorship & sponsorship</b> \u2014 are you growing the next generation?, '
    '(5) <b>Communication & writing</b> \u2014 can you write strategy docs that move people?</p>'
    '<p class="mb-3"><b>Company emphasis:</b> <b>Google</b>: Cross-team technical leadership, '
    'design doc culture, strategic thinking. Promotion committees evaluate "area impact" beyond '
    'your team. <b>Amazon</b>: Leadership principles are the interview rubric. "Have backbone; '
    'disagree and commit," "dive deep," "are right a lot." <b>Meta</b>: "Move fast" means '
    'pragmatic decision-making. Staff engineers are expected to set technical direction for '
    'multiple product teams. <b>Netflix</b>: "Highly aligned, loosely coupled" \u2014 strong '
    'context setting but minimal process. Staff engineers act as entrepreneurs within the company.</p>'
    '<p class="mb-3"><b>Key principle:</b> The best Staff+ engineers are force multipliers. '
    'Your impact is not measured by lines of code written or systems built \u2014 it\u2019s '
    'measured by the quality of decisions you influence, the growth of engineers you develop, '
    'and the culture you create. At Staff+ level, your code is strategy, mentorship, and culture.</p>'
  ),
  "sections": S,
  "tags": ["FAANG","staff-plus","engineering-patterns","leadership","strategy","mentorship","career","Staff+"]
}

with open(OUT, "w") as f:
    json.dump(doc, f, indent=2, ensure_ascii=False)

sz = os.path.getsize(OUT)
print(f"Wrote {OUT} ({sz} bytes, {len(S)} sections)")
for i, s in enumerate(S):
    print(f"  {i+1:2d}. {s['title'][:65]:65s} desc={len(s.get('description','')):6d} code={len(s.get('codeBlock','')):6d}")
