import json, os

def bd(text):
    return f"<p>{text}</p>"

def mg(title, items):
    items_html = "".join(f"<li>{i}</li>" for i in items)
    return f"<div class='mb-4 p-4 rounded bg-slate-800/60 border border-slate-700'><h5 class='text-md font-semibold text-sky-300 mb-2'>{title}</h5><ul class='list-disc list-inside space-y-1 text-sm text-slate-300'>{items_html}</ul></div>"

def tb(headers, rows):
    hdrs = "".join(f"<th class='px-4 py-2 text-left text-xs font-medium text-sky-300 uppercase tracking-wider bg-slate-800/80'>{h}</th>" for h in headers)
    rws = "".join(f"<tr class='border-b border-slate-700/50 hover:bg-slate-800/40'>" + "".join(f"<td class='px-4 py-2 text-sm text-slate-300'>{c}</td>" for c in row) + "</tr>" for row in rows)
    return f"<div class='overflow-x-auto mb-4'><table class='min-w-full border-collapse border border-slate-700 rounded-lg'><thead class='bg-slate-800/60'><tr>{hdrs}</tr></thead><tbody class='divide-y divide-slate-700/50'>{rws}</tbody></table></div>"

S = []

S.append({
    "id": "behavioral-staff",
    "title": "Leadership & Influence Without Authority",
    "category": "behavioral",
    "subcategory": "Staff+ Leadership",
    "description": bd("At Staff+ level, your ability to lead without formal authority determines your impact. Unlike senior engineers who execute, Staff+ engineers shape direction by influencing peers, stakeholders, and leadership using technical credibility, strategic communication, and coalition-building.") + tb(["Aspect", "Senior Engineer", "Staff+ Engineer"], [["Scope", "Owns delivery of assigned work", "Defines what work should be done"], ["Authority", "Uses title/role to direct", "Builds consent through trust & data"], ["Communication", "Reports status upward", "Narrates vision across org"], ["Conflict", "Escalates to manager", "Resolves through negotiation"], ["Risk", "Follows established process", "Challenges process when needed"]]) + bd("<b>The Staff+ Influence Toolkit</b>") + mg("Principles", ["Create pull: attract collaborators by framing compelling outcomes", "Build trust through consistent delivery and follow-through", "Leverage social capital: invest in relationships before you need them", "Use data as your authority: let evidence drive decisions", "Find the decider: map decision-making authority for any initiative"]) + bd("<b>Influence Frameworks</b>") + tb(["Framework", "When to Use", "Key Question"], [["Cialdini's 6 Principles", "Persuading resistant teams", "Which principle aligns with their motivation?"], ["SCARF Model", "Navigating organizational change", "How does this threaten status/certainty/autonomy?"], ["Dissent Channel", "Disagreeing with leadership", "Have I built enough credibility to challenge?"], ["Coalition Building", "Driving cross-team initiatives", "Who else benefits and will advocate?"], ["Pre-mortem", "Risk communication", "What would go wrong and how do we prevent it?"]]) + bd("Staff+ engineers influence by making others successful. Your measure is not what you build, but what the organization achieves because of your presence."),
    "language": "text",
    "sections": [{"heading": "Key Leadership Archetypes at Staff+", "content": bd("Leadership manifests differently at Staff+ depending on context and organizational need. Understanding these archetypes helps you adapt your leadership style.") + mg("The Five Archetypes", ["""<b>Tech Lead:</b> Guides teams through complex technical decisions, sets engineering standards, unblocks with architectural clarity""", """<b>Architect:</b> Designs systems that outlast their involvement, focuses on scalability, reliability, and evolvability""", """<b>Strategist:</b> Aligns technical investments with business outcomes, identifies high-leverage opportunities""", """<b>Mentor:</b> Develops future leaders through sponsorship, creates growth opportunities, amplifies team capability""", """<b>Catalyst:</b> Drives organizational change, removes systemic friction, creates new patterns of working"""]) + bd("Most Staff+ engineers blend multiple archetypes. The key is recognizing which mode is needed and switching deliberately.")}],
    "tags": ["behavioral", "leadership", "staff-plus", "influence", "interview-prep"]
})

S.append({
    "id": "behavioral-staff-2",
    "title": "Technical Vision & Strategy Articulation",
    "category": "behavioral",
    "subcategory": "Staff+ Leadership",
    "description": bd("Staff+ engineers are expected to define and communicate technical vision that aligns engineering investments with business outcomes. This requires synthesis of technical trends, organizational context, and strategic thinking.") + bd("<b>Components of a Technical Vision</b>") + tb(["Component", "Description", "Staff+ Level Expectation"], [["Current State", "Honest assessment of today's architecture", "Surface implicit constraints and technical debt"], ["Future State", "Compelling picture of where you're going", "Must inspire and be achievable within constraints"], ["Migration Plan", "Incremental steps to close the gap", "Include risk mitigation and rollback options"], ["Success Metrics", "How you'll measure progress", "Leading and lagging indicators with baselines"], ["Investment Case", "Why this deserves resources", "ROI analysis with opportunity cost comparison"]]) + bd("<b>Strategy Articulation Framework</b>") + mg("Structure", ["Context: Why now? What external/internal forces demand this change?", "Problem: What specific pain or opportunity are you addressing?", "Proposal: What is the technical direction? (not a design, a direction)", "Alternatives: What else was considered and why was it rejected?", "Impact: How does this affect teams, systems, timelines, and business goals?"]) + bd("At Staff+, your vision must survive disagreement. Practice framing it in multiple ways: for executives (ROI, risk), for engineers (architecture, trade-offs), and for product partners (timeline, capabilities)."),
    "language": "text",
    "sections": [{"heading": "Vision Communication by Audience", "content": tb(["Audience", "What They Care About", "How to Frame"], [["Executives (VP+)", "Cost, timeline, competitive advantage, risk reduction", "Business outcomes, ROI, capacity planning, strategic alignment"], ["Director/Manager", "Team impact, dependencies, resourcing, timeline", "Staffing needs, cross-team coordination, milestones"], ["Engineers (IC)", "Technical details, architecture, trade-offs", "Design documents, RFCs, proof of concepts, migration plan"], ["Product Managers", "Features, timelines, customer impact", "Capability roadmap, delivery schedule, trade-off decisions"], ["Customers/Users", "Quality, reliability, new capabilities", "Release notes, migration guides, deprecation timelines"]])}],
    "tags": ["behavioral", "vision", "strategy", "staff-plus", "communication", "interview-prep"]
})

S.append({
    "id": "behavioral-staff-3",
    "title": "Conflict Resolution & Stakeholder Navigation",
    "category": "behavioral",
    "subcategory": "Staff+ Leadership",
    "description": bd("Conflict at Staff+ is inevitable — you'll mediate between competing priorities, technical philosophies, and organizational politics. Your ability to resolve conflict without escalation defines your leadership maturity.") + tb(["Conflict Type", "Common Example", "Staff+ Resolution Approach"], [["Technical disagreement", "Monolith vs microservices for a new feature", "Foster data-driven debate with experiments and metrics"], ["Resource contention", "Two teams need the same SRE capacity", "Frame trade-offs in business terms, find creative sharing"], ["Priority clash", "Product velocity vs engineering excellence", "Quantify technical debt cost, present risk-adjusted roadmap"], ["Personal conflict", "Two senior engineers with working-style friction", "Separate intent from impact, facilitate direct conversation"], ["Org politics", "Team A wants to own Team B's domain", "Clarify ownership boundaries, design handshake interfaces"]]) + bd("<b>Stakeholder Navigation Map</b>") + mg("For each stakeholder, identify:", ["Power: How much formal authority do they have over your initiative?", "Interest: How invested are they in the outcome?", "Position: What do they publicly advocate for?", "Motivation: What underlying needs drive their position?", "Relationship: What is your current trust level with them?"]) + bd("Build a stakeholder matrix and update it quarterly. The most common Staff+ failure is not technical — it's failing to understand the political landscape."),
    "language": "text",
    "sections": [{"heading": "Difficult Conversation Framework", "content": bd("Use this structure for 1:1 conflict resolution conversations:") + mg("Steps", ["""<b>Prepare:</b> Clarify your intent (\"I want us to make the best technical decision\"). Separate facts from interpretations.""", """<b>Open:</b> State the issue neutrally (\"I noticed we have different approaches to the caching layer. Can we explore both?\").""", """<b>Listen:</b> Paraphrase their position until they say \"Yes, that's right.\" Then share yours.""", """<b>Explore:</b> Find the underlying concern. Is it about correctness, maintainability, or something else?""", """<b>Commit:</b> Agree on next steps, even if it's \"let's each prototype and compare metrics next week.\""""])}],
    "tags": ["behavioral", "conflict", "stakeholder", "staff-plus", "interview-prep"]
})

S.append({
    "id": "behavioral-staff-4",
    "title": "Mentorship, Sponsorship & Amplifying Impact",
    "category": "behavioral",
    "subcategory": "Staff+ Leadership",
    "description": bd("At Staff+, your impact multiplies through the success of others. Mentorship (advice/career guidance) and sponsorship (advocacy/opportunity creation) are distinct but equally critical practices.") + tb(["Dimension", "Mentorship", "Sponsorship"], [["Focus", "Growth & skill development", "Advancement & visibility"], ["Output", "Advice, feedback, perspective", "Opportunities, connections, advocacy"], ["Time commitment", "Regular scheduled sessions", "Episodic, high-leverage actions"], ["Risk", "Low — private advice", "High — public reputation on the line"], ["Relationship", "Junior often initiates", "Sponsor proactively invests"], ["Measure", "Mentee's skill growth", "Sponsoree's career progression"]]) + bd("<b>Sponsorship in Action</b>") + mg("Sponsor Behaviors", ["Recommend for stretch assignments and promo committees", "Invite to meetings where decisions happen", "Provide air cover during failures", "Amplify their work in leadership meetings", "Connect them to influential people in your network", "Nominate them for awards, speaking opportunities, and panels"]) + bd("<b>Building a Sponsorship Network</b>") + mg("Strategy", ["""Deliver exceptional work that makes your sponsor look good — sponsorship is reciprocal, not charitable""", "Identify leaders whose values and priorities align with your direction", "Be explicit about your career aspirations so they can advocate effectively", "Regularly share your wins and progress; don't assume they know", "Sponsor others even before you're a Staff+ — it builds the habit and reputation"]) + bd("The strongest signal of Staff+ readiness is not your individual output but the output of the teams and people you've elevated."),
    "language": "text",
    "sections": [{"heading": "Mentoring at Staff+ Level", "content": bd("Move from directive mentoring (\"here's how to do X\") to Socratic mentoring (\"what do you think? what would happen if?\"). The goal is to build judgment, not transfer rote knowledge.") + tb(["Approach", "Description", "Example"], [["Socratic", "Ask questions that build decision-making frameworks", "\"What trade-offs do you see between these two approaches?\""], ["Cognitive apprenticeship", "Externalize your thinking process", "\"Here's how I reason about this kind of problem...\""], ["Action-learning", "Assign real tasks with guided reflection", "\"Try the first approach, and let's review what you learned\""], ["Growth-edge", "Push into discomfort zones", "\"You should present this to the VP-level review\""], ["Reverse mentoring", "Learn from mentee's fresh perspective", "\"What's the new grad perspective on our onboarding process?\""]])}],
    "tags": ["behavioral", "mentorship", "sponsorship", "staff-plus", "career", "interview-prep"]
})

S.append({
    "id": "behavioral-staff-5",
    "title": "Communication & Executive Presence",
    "category": "behavioral",
    "subcategory": "Staff+ Leadership",
    "description": bd("Executive presence is the ability to inspire confidence — in your judgment, your vision, and your ability to execute. It's communicated through clarity, conciseness, and conviction.") + mg("The 4 Pillars of Executive Presence", ["""<b>Clarity:</b> Distill complex topics into crisp narratives. If you can't explain it simply, you haven't understood it well enough.""", """<b>Concision:</b> Respect time constraints. Practice the 30-second version, the 2-minute version, and the 10-minute version of your key messages.""", """<b>Conviction:</b> Express confidence in your recommendations while acknowledging uncertainty. \"I believe this is the right approach because...\" not \"Maybe we could...\"""", """<b>Composure:</b> Stay steady under pressure. When challenged, pause, acknowledge the point, then respond with evidence.""", """<b>Connection:</b> Read the room. Adjust your message based on audience reaction. Engage, don't lecture."""]) + bd("<b>Written Communication at Staff+</b>") + tb(["Document Type", "Audience", "Structure", "Length"], [["Design Doc / RFC", "Engineering team + cross-functional", "Context -> Goals -> Design -> Alternatives -> Risks", "5-15 pages"], ["Strategy Memo", "Director / VP", "Problem -> Analysis -> Recommendation -> Next Steps", "1-2 pages"], ["Status Update", "Executives / Stakeholders", "Key outcomes -> Blockers -> Decisions needed", "5 bullet points"], ["Post-mortem", "Org-wide", "Summary -> Timeline -> Root Cause -> Actions -> Learnings", "1-3 pages"], ["Performance Review", "Manager / Promo committee", "Impact summary -> Key contributions -> Growth areas", "1 page"]]) + bd("At Staff+, writing is your most scalable communication tool. One well-crafted document can align hundreds of engineers."),
    "language": "text",
    "sections": [{"heading": "Presentation to Senior Leadership", "content": bd("Presenting to VPs and Directors requires a different approach than presenting to engineers:") + mg("Golden Rules", ["""<b>Lead with the conclusion:</b> State your recommendation in the first 15 seconds. \"I recommend we adopt a multi-region active-active architecture for the Payments service.\"""", """<b>Frame in business terms:</b> Connect technical decisions to revenue, cost, risk, or customer experience. Avoid implementation details unless asked.""", """<b>Answer the \"so what?\" test:</b> Every slide should answer \"Why does this matter to the business?\"""", """<b>Pre-read the room:</b> Send a 1-page executive summary 24h before the meeting. Use the meeting for decisions, not information sharing.""", """<b>Handle pushback gracefully:</b> Thank them for the question, clarify the underlying concern, address it directly, and re-anchor to the recommendation."""])}],
    "tags": ["behavioral", "communication", "executive-presence", "staff-plus", "interview-prep"]
})

S.append({
    "id": "behavioral-staff-6",
    "title": "Decision-Making: Speed, Quality & Accountability",
    "category": "behavioral",
    "subcategory": "Staff+ Leadership",
    "description": bd("Staff+ engineers make high-stakes decisions under uncertainty. The quality of your decision-making process matters more than any single decision's outcome.") + tb(["Decision Type", "Speed", "Analysis Required", "Who Decides"], [["Type 1 (Reversible)", "Decisive — decide fast", "Lightweight analysis", "You or your team"], ["Type 2 (Irreversible)", "Deliberate — gather data", "Rigorous analysis with alternatives", "You + stakeholders"], ["Type 3 (Strategic)", "Periodic — scheduled review", "Deep analysis with external input", "Leadership + you recommend"], ["Type 4 (Delegated)", "Your team decides", "As much as team needs", "Your team, with your coaching"]]) + bd("<b>Decision-Making Frameworks</b>") + mg("Frameworks", ["""<b>RAPID:</b> Recommend -> Agree -> Perform -> Input -> Decide. Clarify who plays each role to avoid diffusion of responsibility.""", """<b>DACI:</b> Driver -> Approver -> Contributors -> Informed. A lightweight alternative to RAPID for smaller decisions.""", """<b>Decision Log:</b> Document key decisions with rationale, alternatives considered, and expected outcomes. Review quarterly to calibrate your decision quality.""", """<b>Pre-mortem:</b> Assume the decision led to failure and work backward to identify what went wrong. Reveals blind spots.""", """<b>Cost of Delay:</b> Quantify the business cost of indecision. Many decisions are better made quickly with 80% information than slowly with 95%."""]) + bd("The most common Staff+ decision-making anti-pattern is over-analysis. Learn to distinguish between decisions that deserve rigor and those that need speed."),
    "language": "text",
    "sections": [{"heading": "Decision Journaling Practice", "content": bd("Keep a decision journal for 3 months. For each significant decision, record:") + mg("Template", ["""Context: What situation prompted this decision?""", """Options: What alternatives were considered? (including \"do nothing\")""", """Decision: What did you choose and why?""", """Expected outcome: What do you predict will happen?""", """Review: After the outcome is known — was your prediction accurate? What would you do differently?"""]) + bd("Research shows that decision journaling improves calibration by 30-40%. The key is capturing your reasoning <b>before</b> you know the outcome, to combat hindsight bias.")}],
    "tags": ["behavioral", "decision-making", "judgment", "staff-plus", "interview-prep"]
})

S.append({
    "id": "behavioral-staff-7",
    "title": "STAR+ Method: Answering Behavioral Questions at Staff+",
    "category": "behavioral",
    "subcategory": "Staff+ Interviewing",
    "description": bd("The STAR method (Situation, Task, Action, Result) is the foundation, but Staff+ behavioral questions require a deeper layer — STAR+. You must demonstrate judgment, scale of impact, and leadership maturity.") + tb(["Layer", "Standard STAR", "STAR+ for Staff+"], [["Situation", "Brief context", "Org-wide context: team size, product phase, technical constraints, stakeholders involved"], ["Task", "Your responsibility", "Why you specifically? What make this your problem to solve?"], ["Action", "What you did", "Your reasoning process, alternatives considered, trade-offs made, how you brought others along"], ["Result", "What happened", "Measurable impact, lessons learned, how you applied insights afterward, second-order effects"], ["+ Judgment", "N/A", "What made this a Staff+ challenge? Ambiguity? Scale? Cross-team? Organizational resistance?"], ["+ Growth", "N/A", "How did this change your approach? What would you do differently with hindsight?"]]) + bd("<b>High-Impact Behavioral Topics at Staff+</b>") + mg("Must-Prepare Stories", ["""<b>Technical leadership:</b> A time you drove technical direction across multiple teams""", """<b>Conflict resolution:</b> A significant disagreement you resolved without escalation""", """<b>Failure & recovery:</b> A major mistake or outage you led recovery from""", """<b>Strategic impact:</b> A decision that saved significant cost, time, or risk at org scale""", """<b>People development:</b> An engineer you mentored/sponsored who advanced significantly""", """<b>Influence without authority:</b> A cross-functional initiative where you had no formal power""", """<b>Handling ambiguity:</b> A project with unclear requirements that you defined and delivered""", """<b>Innovation:</b> A novel approach or tool you introduced to solve a systemic problem""", """<b>Bias for action:</b> A time you made a high-stakes decision with incomplete information"""]) + bd("Prepare 12-15 stories that cover these topics. Each story should have a STAR+ structure ready, and you should be able to adapt it to different question phrasings."),
    "language": "text",
    "sections": [{"heading": "Sample STAR+ Response: Technical Leadership", "content": bd("<b>Question:</b> \"Tell me about a time you drove a complex technical initiative across multiple teams.\"") + bd("<b>Situation:</b> \"At Amazon, I noticed that our fulfillment center inventory system had a 2.3% data inconsistency rate across 4 regional databases. This caused 15+ P2 escalations monthly and wasted ~300 engineer-hours/week on reconciliation.\"") + bd("<b>Task:</b> \"As the Staff engineer for the Inventory Platform, I needed to unify the data model and eliminate inconsistencies without disrupting 24/7 fulfillment operations.\"") + bd("<b>Action:</b> \"First, I convened a working group with the 4 regional tech leads and our SRE team. I presented a data-driven analysis of failure patterns and proposed a leader-based replication model with a unified schema. Two leads opposed it due to migration risk. Instead of escalating, I ran a 2-week proof-of-concept that demonstrated consistent reads with <10ms latency overhead. I then negotiated a rolling migration schedule that minimized peak-season risk.\"") + bd("<b>Result:</b> \"Inconsistencies dropped to 0.02%. P2 escalations went from 15/month to 0. We recovered ~250 engineer-hours/week. The pattern became the standard for other platform teams.\"") + bd("<b>+ Judgment:</b> \"The key insight was that technical correctness was secondary to operational continuity. By prioritizing a safe migration over a perfect architecture, I maintained business trust and enabled the long-term vision.\"") + bd("<b>+ Growth:</b> \"I learned to invest more heavily in pre-work (data analysis, PoC) before proposing changes. The proof-of-concept removed emotional debate and replaced it with objective data.\"")}],
    "tags": ["behavioral", "star-method", "interview-prep", "staff-plus"]
})

S.append({
    "id": "behavioral-staff-8",
    "title": "Storytelling & Narrative Construction",
    "category": "behavioral",
    "subcategory": "Staff+ Interviewing",
    "description": bd("Facts tell, stories sell — nowhere is this truer than Staff+ behavioral interviews. Your stories must be compelling, memorable, and demonstrate seniority in under 2 minutes.") + bd("<b>The Story Spine for Staff+</b>") + mg("Structure", ["""<b>Setup:</b> Establish the stakes. \"We were processing $5B in annual transactions through a system designed for $500M.\"""", """<b>Tension:</b> What made this hard? \"The VP wanted a 3-month fix. My analysis showed we needed 9 months to avoid catastrophic risk.\"""", """<b>Choice:</b> The moment where your judgment matters. \"I decided to present both options with a quantified risk analysis rather than just taking the order.\"""", """<b>Synthesis:</b> Reconnect to broader impact. \"This taught me that part of Staff+ responsibility is knowing when to say no — and how to frame it so leadership can say yes.\""""]) + bd("<b>Engineering Your Narrative</b>") + tb(["Technique", "Why It Works", "Example"], [["Specificity", "Details signal authenticity", "\"The query had 47 JOINs and took 23 seconds\" vs \"it was slow\""], ["Contrast", "Highlights difficulty and impact", "\"Before: 47 hours of manual work. After: 12-second automated report.\""], ["Stakes", "Makes the outcome matter", "\"This decision affected 200 engineers and $12M annual infrastructure spend.\""], ["Transformation", "Shows personal growth", "\"I used to optimize for technical elegance. Now I optimize for organizational velocity.\""], ["Brevity", "Respects time and shows clarity", "\"We had a hard choice: ship fast with tech debt, or refactor and delay. Here's how I navigated it.\""]]) + bd("Practice your stories out loud. Record yourself. Aim for 90-120 seconds per story. Cut ruthlessly."),
    "language": "text",
    "sections": [{"heading": "Common Storytelling Traps at Staff+ Level", "content": tb(["Trap", "Why It Hurts", "Fix"], [["Vague outcomes", "\"The project was successful\" — doesn't demonstrate scale", "\"We reduced p99 latency from 2.3s to 410ms, saving $840K/year\""], ["Too much technical detail", "Lost audience — especially non-technical interviewers", "Lead with impact, offer technical depth if asked"], ["Missing the \"I\"", "\"We did this\" repeated too often — hides your contribution", "Use \"I\" for your specific actions, \"we\" for context"], ["No conflict", "Sounds too easy — doesn't prove worth", "Include the tension: \"The team was split. I had to build consensus.\""], ["Happy ending only", "Lacks authenticity — no learning", "Include what went wrong and what you'd change"], ["Hijacking credit", "Signals poor collaboration", "\"I led the initiative. The team's execution was excellent.\" attributes appropriately"]])}],
    "tags": ["behavioral", "storytelling", "narrative", "interview-prep", "staff-plus"]
})

S.append({
    "id": "behavioral-staff-9",
    "title": "Handling Ambiguity & Uncertainty",
    "category": "behavioral",
    "subcategory": "Staff+ Leadership",
    "description": bd("Ambiguity is the default state at Staff+. You'll be handed fuzzy problems without clear requirements and expected to define the path forward. How you navigate uncertainty is a key signal of Staff+ readiness.") + tb(["Ambiguity Type", "Example", "Staff+ Response"], [["Unclear requirements", "\"Improve our data pipeline reliability\"", "Define reliability metrics (SLOs), current baselines, and achievable targets before proposing solutions"], ["Conflicting priorities", "Product vs platform vs security all disagree", "Map stakeholders, find shared success criteria, propose sequenced investment"], ["Unknown technology", "\"We should use this new database\" but no one knows it", "Run a systematic evaluation: benchmark, failover test, cost projection, team learning curve"], ["Org restructuring", "Teams merging, roles unclear", "Focus on what you can control: your team's output and relationships. Clarify scope with leadership."], ["New domain", "You're asked to own a system you've never worked on", "Rapid learning: read all existing docs, interview key people, shadow incidents, propose small improvements first"]]) + bd("<b>The Ambiguity Navigation Framework</b>") + mg("Process", ["""<b>1. Define the question:</b> What exactly needs to be decided? \"What does 'reliable' mean?\" is more valuable than \"Which database should we use?\"""", """<b>2. Identify what you know:</b> Facts, data points, existing constraints, stakeholder preferences""", """<b>3. Explicitly list what you don't know:</b> Gaps to fill with highest leverage""", """<b>4. Run small experiments:</b> Prototypes, analysis, surveys — reduce uncertainty with minimal investment""", """<b>5. Make a recommendation with confidence intervals:</b> \"I'm 70% confident this is right. Here are the risks if I'm wrong.\""""]) + bd("The key is not eliminating ambiguity — it's demonstrating productive navigation of it. Staff+ engineers make progress in the fog."),
    "language": "text",
    "sections": [{"heading": "Decision Trees for Uncertainty", "content": bd("When faced with high uncertainty, use decision trees to structure your thinking:") + mg("Decision Tree Approach", ["""<b>Branch 1: Optimistic scenario</b> — What if everything goes right? What's the outcome? What's the investment?""", """<b>Branch 2: Pessimistic scenario</b> — What if everything goes wrong? What's the downside? What's the mitigation?""", """<b>Branch 3: Most likely scenario</b> — What's the realistic outcome based on historical patterns?""", """<b>Value of information</b> — What would you pay (in time/cost) to know which branch you're on?""", """<b>Decision threshold</b> — At what confidence level would you commit to a path vs continue exploring?"""]) + bd("This approach demonstrates sophisticated risk thinking and separates you from engineers who either freeze or act impulsively under uncertainty.")}],
    "tags": ["behavioral", "ambiguity", "uncertainty", "staff-plus", "interview-prep"]
})

S.append({
    "id": "behavioral-staff-10",
    "title": "Cross-Functional Collaboration",
    "category": "behavioral",
    "subcategory": "Staff+ Leadership",
    "description": bd("Staff+ engineers work at the intersection of engineering, product, design, data science, legal, compliance, and business. Effective cross-functional collaboration is a force multiplier.") + tb(["Partner Role", "Their Priority", "How to Collaborate Effectively", "Common Pitfall"], [["Product Manager", "Feature velocity, customer impact", "Involve early in technical constraints, educate on tech debt", "Dismissing their timeline concerns as \"business pressure\""], ["Designer", "UX consistency, user research", "Share technical constraints before they design; discuss trade-offs", "Blaming design for implementation complexity"], ["Data Scientist", "Statistical rigor, experiment design", "Partner on metrics definition, instrumentation requirements", "Treating them as a service provider instead of collaborator"], ["Legal/Compliance", "Risk minimization, regulatory compliance", "Proactively flag architecture decisions with compliance impact", "Bypassing them until launch — causes delays"], ["Program Manager", "Timeline, dependencies, risk tracking", "Provide accurate estimates, flag risks early, respect rituals", "Hiding delays until the last minute"], ["SRE", "Stability, reliability, on-call sustainability", "Design for operability, share incident response, reduce toil", "Throwing systems over the wall after launch"]]) + bd("<b>Building Cross-Functional Trust</b>") + mg("Trust Accelerators", ["""<b>Speak their language:</b> Frame technical decisions in terms that matter to each partner (cost, risk, timeline, user impact)""", """<b>Be predictable:</b> Deliver on commitments. If you can't, communicate early. Reliability builds more trust than heroics.""", """<b>Give credit generously:</b> Amplify your partners' contributions in leadership meetings. It pays back tenfold.""", """<b>Learn their constraints:</b> Understand what makes their job hard. A PM who knows you understand their roadmap pressure will move mountains for you.""", """<b>Create shared wins:</b> Design projects where success requires genuine cross-functional collaboration, not just parallel work."""]) + bd("At Staff+, your ability to generate alignment across functions is a superpower. It's also rare — most engineers never develop it."),
    "language": "text",
    "sections": [{"heading": "Navigating Cross-Functional Conflict", "content": bd("When cross-functional partners disagree, Staff+ engineers often serve as the neutral arbiter:") + mg("Mediation Framework", ["""<b>1. Separate positions from interests:</b> "The PM wants to launch June 1 (position) because the board committed to a revenue target (interest).\"""", """<b>2. Find the overlapping Venn:</b> Where do product velocity, engineering quality, design consistency, and business risk intersect?""", """<b>3. Propose creative options:</b> Brainstorm solutions that serve multiple interests. Feature flags, phased rollouts, canary launches, etc.""", """<b>4. Escalate only when necessary:</b> Frame escalation as a request for prioritization, not a complaint about the other team.""", """<b>5. Document the agreement:</b> Write down what was decided and why. This prevents re-litigation and provides clarity for all."""])}],
    "tags": ["behavioral", "cross-functional", "collaboration", "staff-plus", "interview-prep"]
})

S.append({
    "id": "behavioral-staff-11",
    "title": "Culture Fit & Value Alignment at FAANG",
    "category": "behavioral",
    "subcategory": "Staff+ Interviewing",
    "description": bd("Each FAANG company has a distinct culture. Staff+ interviews test not just whether you can do the job, but whether you'll thrive in their specific environment.") + tb(["Company", "Core Value", "Staff+ Interview Focus", "Common Cultural Question"], [["Google", "Technical excellence, data-driven", "Systems thinking, comfort with ambiguity, cross-functional influence", "\"Tell me about a time you disagreed with your manager about a technical approach\""], ["Amazon", "Customer obsession, high standards, bias for action", "Delivering results at scale, ownership beyond scope, handling disagreement", "\"Tell me about a time you significantly improved a process or system\""], ["Meta", "Move fast, be open, focus on impact", "Speed of execution, adaptability, prioritizing what matters most", "\"Tell me about your biggest impact and how you achieved it\""], ["Netflix", "Freedom and responsibility, context over control", "High-judgment decision-making, direct communication, self-motivation", "\"Tell me about a hard decision you made without consensus\""], ["Apple", "Design-led, customer intuition, vertical integration", "Craftsmanship, deep technical understanding, cross-functional collaboration", "\"Tell me about a time you fought for quality over speed\""], ["Microsoft", "Growth mindset, inclusive, mission-driven", "Collaborative leadership, customer empathy, platform thinking", "\"Tell me about a time you influenced a team you didn't manage\""]]) + bd("<b>Assessing Cultural Fit in Your Response</b>") + mg("Demonstrate Fit Through", ["""<b>Leadership principles:</b> Explicitly reference the company's leadership principles or values in your answers""", """<b>Specificity to their context:</b> Show you understand their scale, challenges, and technical stack""", """<b>Values alignment:</b> Your natural approach should reflect their values — not in a forced way, but authentically""", """<b>Questions you ask:</b> The questions you ask interviewers reveal your priorities. Ask about their challenges, culture, and growth.""", """<b>Self-awareness:</b> Acknowledge where your style differs from their culture and explain how you adapt"""]) + bd("Cultural fit is not about conforming — it's about finding environments where your natural strengths are valued and your growth edges are challenged."),
    "language": "text",
    "sections": [{"heading": "Leadership Principles Deep Dive", "content": bd("Amazon's Leadership Principles are the most explicit example, but every FAANG has their version. Here's how to prepare:") + tb(["Leadership Principle", "Common Question", "Key Themes to Hit"], [["Customer Obsession (Amazon)", "\"Tell me about a time you prioritized customer needs over internal constraints\"", "User research data, customer feedback, trade-offs made for user experience"], ["Think Big (Amazon)", "\"What's the most impactful technical vision you've driven?\"", "Scale, ambition, business alignment, measurable outcomes"], ["Bias for Action (Amazon)", "\"Tell me about a decision you made quickly with incomplete information\"", "Speed of decision, risk assessment, outcome, learning"], ["Move Fast (Meta)", "\"How have you balanced speed and quality?\"", "Feature flags, phased rollouts, acceptable risk levels"], ["Direct Communication (Netflix)", "\"Tell me about a conversation you had that most people would avoid\"", "Candor, respect, preparation, outcome"], ["Growth Mindset (Microsoft)", "\"Tell me about a time you learned from a failure\"", "Specific failure, analysis, changes made, result of change"]])}],
    "language": "text",
    "sections": [{"heading": "Handling \"Tell Me About Yourself\" at Staff+", "content": bd("This opening question sets the tone. Your answer should be a mini-narrative that connects your career trajectory, key achievements, and why this role at this company.") + mg("Structure", ["""<b>30-second version:</b> \"I'm a Staff engineer at X where I've spent the last 4 years building Y. Previously at Z, I led W. I'm excited about this opportunity because...\"""", """<b>2-minute version:</b> Add your 2 most impactful stories with scale and results. End with what you're looking for next.""", """<b>Key principle:</b> Connect your past to their future. Show how your experience prepares you for their specific challenges.""", """<b>Avoid:</b> Starting with your childhood, listing every job chronologically, being too technical, or being too vague.""", """<b>Do:</b> Start with your current role, hit your peak impact, and bridge to why this role is the logical next step."""])}],
    "tags": ["behavioral", "culture-fit", "faang", "staff-plus", "interview-prep"]
})

S.append({
    "id": "behavioral-staff-12",
    "title": "Handling Failure, Mistakes & Post-Mortems",
    "category": "behavioral",
    "subcategory": "Staff+ Leadership",
    "description": bd("How you handle failure is one of the strongest signals in a Staff+ interview. Interviewers want to see ownership, learning, and systemic thinking — not deflection or blame.") + bd("<b>How NOT to Talk About Failure</b>") + mg("Anti-Patterns", ["""<b>Blaming others:</b> \"The PM changed requirements\" or \"The testing team missed it\" — this signals lack of ownership""", """<b>Trivial failures:</b> \"I forgot to push a commit once\" — doesn't demonstrate significant responsibility""", """<b>Too vague:</b> \"The project didn't go as planned\" — no depth, no learning""", """<b>Defensive framing:</b> \"It wasn't really my fault because...\" — sounds like you haven't processed the failure""", """<b>Perfect recovery:</b> \"I fixed it immediately and no one noticed\" — failure is more credible when you own the impact"""]) + bd("<b>The Staff+ Failure Response Framework</b>") + mg("Response Structure", ["""<b>1. Own it explicitly:</b> \"This was my mistake. I owned the architecture decision that led to the outage.\"""", """<b>2. Show the stakes:</b> \"We had a 47-minute P0 incident affecting 3M users during Black Friday.\"""", """<b>3. Describe your analysis:</b> \"I traced the root cause to a cache invalidation race condition I introduced when optimizing for throughput.\"""", """<b>4. Demonstrate systemic fix:</b> \"Beyond fixing the immediate bug, I added a new testing class for concurrent cache scenarios, documented the pattern, and gave a tech talk on cache safety.\"""", """<b>5. Share the lesson:</b> \"I now require all throughput optimizations to include a concurrency safety review. This incident changed our team's approach to performance work.\""""]) + bd("The strongest failure stories don't minimize the failure — they demonstrate that you can fail at scale, learn deeply, and prevent recurrence systemically."),
    "language": "text",
    "sections": [{"heading": "Sample Failure Response (STAR+)", "content": bd("<b>Question:</b> \"Tell me about a time something went wrong in a project you led.\"") + bd("<b>Situation:</b> \"I was leading the migration of our payment processing system from a monolithic batch processor to a real-time event-driven architecture handling $2B/month.\"") + bd("<b>Task:</b> \"The migration needed zero downtime and zero data loss — any mistake meant financial reconciliation nightmares.\"") + bd("<b>Action:</b> \"I designed a dual-write strategy that would write to both systems during migration. However, I missed a subtle ordering guarantee: the new system required exactly-once semantics, but the dual-write could produce duplicates under certain failure conditions. I didn't discover this until we were 40% through the migration.\"") + bd("<b>Result:</b> \"We had 0.03% duplicate transactions — about 1,200 duplicates. I immediately halted the migration, rolled back the dual-write, and spent 72 hours with the team redesigning the migration to use a transactional outbox pattern with idempotency keys.\"") + bd("<b>+ Judgment:</b> \"The root cause was my assumption that the new system's exactly-once guarantee would extend to the migration path. I should have tested the migration path specifically, not just the new system in isolation.\"") + bd("<b>+ Growth:</b> \"I now write a 'migration safety checklist' that covers ordering, idempotency, rollback, and data validation for every migration I lead. This checklist has been adopted by the org.\"")}],
    "language": "text",
    "sections": [{"heading": "Post-Mortem Culture at Staff+", "content": bd("Staff+ engineers set the tone for their team's post-mortem culture. A blameless post-mortem is a Staff+ responsibility, not an SRE responsibility.") + mg("Staff+ Post-Mortem Ownership", ["""Lead by example: Write post-mortems for your own mistakes first, with as much rigor as you'd expect from others""", """Focus on system design, not individual error: Frame findings as \"The system allowed this failure\" not \"Engineer X made a mistake\"""", """Track action items: Post-mortems without completed action items are theater. Hold yourself and others accountable.""", """Share learnings org-wide: A post-mortem that only your team learns from is a missed opportunity for org-wide improvement.""", """Celebrate good post-mortems: Praise teams that publish honest, thorough post-mortems. This incentivizes transparency."""])}],
    "tags": ["behavioral", "failure", "post-mortem", "blameless", "staff-plus", "interview-prep"]
})

S.append({
    "id": "behavioral-staff-13",
    "title": "Building & Leading High-Performing Teams",
    "category": "behavioral",
    "subcategory": "Staff+ Leadership",
    "description": bd("Staff+ engineers are force multipliers. You don't manage people, but you shape the teams, processes, and culture that enable high performance.") + bd("<b>The Staff+ Role in Team Building</b>") + mg("Key Responsibilities", ["""<b>Set technical standards:</b> Define what \"good\" looks like — code review standards, architecture patterns, testing expectations""", """<b>Create growth paths:</b> Design career progression for ICs on your team, identify stretch assignments, provide sponsorship""", """<b>Shape team culture:</b> Model the behaviors you want to see — psychological safety, intellectual honesty, bias for action""", """<b>Improve team processes:</b> Fix broken rituals, introduce effective practices (design reviews, RFC process, incident review)""", """<b>Build onboarding excellence:</b> New team members should become productive in weeks, not months""", """<b>Facilitate decision-making:</b> Ensure the team makes decisions efficiently, documents them, and learns from outcomes"""]) + bd("<b>High-Performance Team Characteristics</b>") + tb(["Dimension", "Low-Performing Team", "High-Performing Team"], [["Psychological safety", "Members afraid to disagree", "Healthy debate is encouraged and expected"], ["Dependability", "Missed deadlines, inconsistent quality", "Consistent delivery, reliable estimates"], ["Structure & clarity", "Unclear roles and decision authority", "Clear ownership, explicit decision makers"], ["Meaning of work", "Tasks feel disconnected from impact", "Team understands how their work drives business goals"], ["Impact of work", "No feedback on outcomes", "Regular data on how their work affects users"]]) + bd("Google's Project Aristotle found that psychological safety was the #1 predictor of team effectiveness. At Staff+, you are the primary architect of safety on your team."),
    "language": "text",
    "sections": [{"heading": "Diagnosing Team Health", "content": bd("Staff+ engineers should regularly assess team health using multiple signals:") + tb(["Signal", "What to Watch For", "Intervention"], [["DORA metrics", "Low deployment frequency, high lead time, high change failure rate", "Invest in CI/CD, reduce batch size, improve test coverage"], ["Sprint velocity trend", "Declining or erratic velocity", "Address technical debt, team churn, or scope creep"], ["On-call metrics", "Alert fatigue, high MTTR, frequent wake-ups", "Reduce toil, improve monitoring, invest in resilience"], ["1:1 sentiment", "Frustration, burnout signals, disengagement", "Address workload, provide growth opportunities, adjust expectations"], ["Cross-team feedback", "Complaints from partner teams", "Improve communication, clarify interfaces, document APIs"], ["Retrospective health", "Retros feel performative or are skipped", "Revamp retro format, ensure action items get closure"]])}],
    "tags": ["behavioral", "team-building", "team-health", "staff-plus", "interview-prep"]
})

S.append({
    "id": "behavioral-staff-14",
    "title": "Managing Technical Debt & Legacy Systems",
    "category": "behavioral",
    "subcategory": "Staff+ Leadership",
    "description": bd("Technical debt management is a Staff+ responsibility. Unlike junior engineers who can ignore legacy systems, Staff+ must strategically invest in reducing debt while maintaining feature velocity.") + tb(["Debt Type", "Example", "Cost", "When to Pay Down"], [["Code-level", "Duplicated logic, insufficient tests, poor naming", "Increased bug rate, slower feature development", "Continuously — build quality into the definition of done"], ["Architecture-level", "Monolith that should be services, wrong DB for workload", "High change friction, scaling bottlenecks", "When it blocks business capabilities or creates SLO risk"], ["Infrastructure-level", "Manual deployment, no monitoring, fragile build pipeline", "Incidents, slow recovery, developer frustration", "Invest proportionally to team size and release frequency"], ["Knowledge-level", "Undocumented systems, bus factor of 1, no runbooks", "Onboarding time, incident response time", "Whenever a person leaves or a system grows beyond 1 team"], ["People-level", "Key-person dependencies, burnout, unreviewed decisions", "Team fragility, stalled growth", "Continuously — through rotation, documentation, and pairing"]]) + bd("<b>The Staff+ Debt Repayment Framework</b>") + mg("Prioritization", ["""<b>1. Quantify the cost:</b> \"This design pattern adds 3 days per sprint in manual testing. That's 15% of team capacity.\"""", """<b>2. Align with business:</b> Connect debt to business outcomes. \"This architecture limits us to 5 concurrent mobile features. Competitor does 15.\"""", """<b>3. Propose incremental investment:</b> Not a \"big rewrite.\" Gradual improvement with measurable milestones.""", """<b>4. Create friction for new debt:</b> Architectural review gates, mandatory design docs, tech debt tracking in the backlog.""", """<b>5. Celebrate debt reduction:</b> When a system becomes easier to work in, make it visible. Positive reinforcement sustains investment."""]) + bd("The best way to manage tech debt is to never accumulate it unintentionally. Design with future maintenance in mind, and defend that investment when pressured to cut corners."),
    "language": "text",
    "sections": [{"heading": "The Rewrite vs Refactor Decision", "content": bd("One of the hardest Staff+ judgment calls is when to rewrite vs refactor. Joel Spolsky's \"Things You Should Never Do\" warns against rewrites, but sometimes they're the right call.") + tb(["Factor", "Refactor (Incremental)", "Rewrite (Greenfield)"], [["System size", "< 50K LOC or well-modularized", "> 500K LOC with tight coupling"], ["Team expertise", "Team knows the system well", "Team has lost understanding / high turnover"], ["Business need", "System mostly works, needs extension", "System cannot support required capabilities"], ["Risk tolerance", "Low — cannot afford extended downtime", "Medium — can run in parallel during development"], ["Migration path", "Clear gradual replacement strategy", "No viable incremental path (rare)"], ["Technical maturity", "Existing tests, modular design", "No tests, no separation of concerns"], ["Cost", "Lower upfront, consistent over time", "Higher upfront, potentially lower long-term"]]) + bd("When in doubt, invest in making the system easier to refactor (tests, modular boundaries, documentation) rather than planning a rewrite. Most rewrites fail because they underestimate the complexity encoded in the legacy system.")}],
    "language": "text",
    "sections": [{"heading": "Cost-Benefit Analysis Template", "content": bd("When proposing a technical debt investment, use this template to make the business case:") + mg("Template", ["""<b>Current cost:</b> \"This legacy system costs us $X/month in: (1) incident response, (2) slow feature delivery, (3) onboarding time.\"""", """<b>Proposed investment:</b> \"I recommend a 3-phase, 6-month investment of Y engineer-months.\"""", """<b>Expected return:</b> \"After this investment, we expect: (1) 50% fewer P2+ incidents, (2) 30% faster feature delivery, (3) payback in 8 months.\"""", """<b>Risk of inaction:</b> \"If we don't invest, we project: (1) increasing incident rate as system ages, (2) losing 2-3 engineers/quarter to frustration, (3) missing Q4 OKRs.\""""])}],
    "tags": ["behavioral", "tech-debt", "legacy-systems", "staff-plus", "interview-prep"]
})

S.append({
    "id": "behavioral-staff-15",
    "title": "Staff+ Promotion & Career Growth",
    "category": "behavioral",
    "subcategory": "Staff+ Career",
    "description": bd("Navigating the Staff+ promotion process requires understanding how promotion committees evaluate candidates, what evidence they need, and how to build your packet strategically.") + bd("<b>How Staff+ Promotions Work</b>") + tb(["Step", "What Happens", "Staff+ Candidate Action"], [["1. Self-assessment", "Review your impact against the promotion rubric", "Collect evidence: design docs, impact metrics, cross-team influence"], ["2. Manager endorsement", "Your manager writes a promo doc making the case", "Work with manager for 6+ months before promo cycle — align on narrative"], ["3. Peer feedback", "4-8 peers provide written feedback on your impact", "Cultivate a strong network of peers who have seen your work firsthand"], ["4. Promo committee", "A panel of Staff+ and Principal engineers reviews your packet", "Your achievements must be clear without verbal explanation"], ["5. Calibration", "Committee compares you against other candidates", "Be in the top 25% of the current Staff cohort, not meeting the minimum"]]) + bd("<b>Building Your Promotion Packet</b>") + mg("Key Elements", ["""<b>Narrative:</b> Your career story that connects your achievements to increasing scope and impact""", """<b>Impact artifacts:</b> Design documents you authored, systems you architected, org changes you drove""", """<b>Quantified results:</b> Every claim needs a number. \"Improved latency\" is weak. \"Reduced p99 latency from 2.1s to 180ms across 14 services\" is strong.""", """<b>Scope evidence:</b> Show that you operate beyond your team. Cross-team initiatives, organizational influence, mentorship of Staff+ candidates.""", """<b>Peer testimonials:</b> Ask peers to write about specific instances where you demonstrated Staff+ behaviors.""", """<b>Growth trajectory:</b> Show that your impact is accelerating, not plateauing."""]) + bd("The most common promo packet mistake is showing Senior Engineer impact (delivery excellence) rather than Staff+ impact (strategic direction, organizational leverage)."),
    "language": "text",
    "sections": [{"heading": "FAANG-Specific Promotion Rubrics", "content": tb(["Dimension", "Senior (L5/E5)", "Staff (L6/E6)", "Senior Staff (L7/E7)"], [["Scope", "Owns a component or feature area", "Owns a system or multi-team domain", "Owns an org-wide or company-wide domain"], ["Impact", "Improves existing systems", "Defines new systems and direction", "Transforms org capability and technical strategy"], ["Autonomy", "Works independently within team", "Defines what the team should build", "Defines what the org should invest in"], ["Influence", "Influences within team", "Influences across teams and org boundaries", "Influences company technical direction"], ["Mentorship", "Mentors junior engineers", "Develops Senior engineers, sponsors emerging leaders", "Builds Staff+ pipeline, shapes engineering culture"], ["Judgment", "Makes good technical decisions within domain", "Makes high-judgment decisions with org-wide impact", "Makes decisions that shape company trajectory"], ["Communication", "Clear written and verbal communication", "Compelling narratives that align organizations", "Thought leadership that changes industry practice"]])}],
    "tags": ["behavioral", "promotion", "career", "staff-plus", "rubric", "interview-prep"]
})

S.append({
    "id": "behavioral-staff-16",
    "title": "Staff+ Behavioral Interview Strategy",
    "category": "behavioral",
    "subcategory": "Staff+ Interviewing",
    "description": bd("The Staff+ behavioral interview loop differs from senior-level loops. You'll face multiple rounds focused on leadership, conflict, strategy, and failure — each requiring a different preparation approach.") + bd("<b>Common Staff+ Behavioral Loop Structure</b>") + tb(["Round", "Focus", "Example Questions"], [["Leadership & Vision", "How you drive direction and align others", "\"Describe a technical vision you set and how you got buy-in\""], ["Conflict & Influence", "How you handle disagreement without authority", "\"Tell me about a significant disagreement with a peer or stakeholder\""], ["Failure & Learning", "How you handle mistakes and grow", "\"Tell me about a project that didn't go as planned\""], ["Ambiguity & Strategy", "How you navigate uncertainty", "\"Tell me about a time you had to make a decision with limited information\""], ["Culture & Values", "How you align with company principles", "\"Tell me about a time you prioritized long-term quality over short-term speed\""], ["Cross-functional", "How you collaborate beyond engineering", "\"Tell me about a time you partnered with product, design, or business teams\""], ["Career & Motivation", "Why this level, this company, this team", "\"Why are you interested in Staff+ now, and why here?\""]]) + bd("<b>Preparation Strategy</b>") + mg("90-Day Prep Plan", ["""<b>Days 1-30:</b> Write out 15 STAR+ stories spanning all categories. Practice each story three times out loud. Record and review.""", """<b>Days 31-60:</b> Mock interviews — 6+ sessions with peers, mentors, or coaches. Focus on getting feedback about Staff+ signal, not just story quality.""", """<b>Days 61-75:</b> Deep-dive company research. Study their leadership principles, recent tech blog posts, engineering culture. Adapt your stories to the specific company.""", """<b>Days 76-90:</b> Light review. Rehearse your top 5 most-likely stories. Prepare thoughtful questions for interviewers. Sleep and exercise.""", """<b>The day before:</b> Review your story list. Don't try to memorize — you want authentic recall, not a scripted performance."""]) + bd("The difference between a Senior and Staff+ behavioral performance: Seniors describe <b>what</b> they did. Staff+ candidates explain <b>why</b> they chose that path over alternatives, showing judgment and self-awareness."),
    "language": "text",
    "sections": [{"heading": "Signs You're Performing at Staff+ Level", "content": tb(["Signal", "Senior Behavior", "Staff+ Behavior"], [["Answer structure", "STAR format with clear actions", "STAR+ with judgment, alternatives considered, systemic learning"], ["Problem framing", "Accepts the problem as given", "Questions and reframes the problem: \"Is this the right problem to solve?\""], ["Conflict handling", "Describes escalation path", "Describes resolution path: built consensus, found creative compromise"], ["Metrics focus", "Team-level or project-level metrics", "Org-level or company-level metrics with attention to unintended consequences"], ["Learning emphasis", "\"I learned X\" at the end", "Connects learning to changed behavior: \"I now approach Y problems differently. Here's an example.\""], ["Self-awareness", "Acknowledges limitations", "Proactively seeks growth: \"I ask my team for feedback on this and track progress.\""], ["Ownership", "Owned their part", "Owned the outcome, including parts they didn't directly control"], ["Vision", "Describes what they built", "Describes what they made possible for others to build"]])}],
    "language": "text",
    "sections": [{"heading": "Questions to Ask Your Interviewers", "content": bd("The questions you ask signal your level. At Staff+, ask questions that demonstrate strategic thinking and organizational awareness:") + mg("Strong Staff+ Questions", ["""\"How does this organization balance investment in new features vs reducing technical debt?\"""", """\"What's the most significant technical challenge the team will face in the next 12 months?\"""", """\"How does the company define and measure Staff+ impact?\"""", """\"What's the decision-making process for cross-team technical initiatives?\"""", """\"What's something you wish you had known when you joined at this level?\""""]) + mg("Avoid", ["Questions answered by 5 minutes of research", "\"What does your team do?\" (too broad)", "\"What's the work-life balance?\" (signals wrong priorities)", "\"When will I be promoted?\" (premature)", "Asking zero questions (worst signal of all)"])}],
    "tags": ["behavioral", "interview-strategy", "preparation", "staff-plus"]
})

S.append({
    "id": "behavioral-staff-17",
    "title": "References & Further Reading",
    "category": "behavioral",
    "subcategory": "Staff+ Career",
    "description": bd("This guide synthesizes patterns from Staff+ engineers at FAANG and other top tech companies. The following resources provide deeper dives into specific topics.") + mg("Books", ["""<b>Staff Engineer: Leadership Beyond the Management Track</b> by Will Larson — The definitive guide to the Staff+ role, archetypes, and day-to-day work""", """<b>The Staff Engineer's Path</b> by Tanya Reilly — Practical advice on navigating the Staff+ role including big-picture thinking, managing projects, and staying aligned""", """<b>Influence Without Authority</b> by Allan Cohen and David Bradford — Classic text on building cross-organizational influence""", """<b>Dare to Lead</b> by Brené Brown — Research-based approach to vulnerability, trust, and courageous leadership""", """<b>Thinking in Bets</b> by Annie Duke — Decision-making under uncertainty, calibration and decision journaling""", """<b>The Culture Map</b> by Erin Meyer — Cross-cultural communication patterns essential for global FAANG teams""", """<b>Turn the Ship Around</b> by L. David Marquet — Leadership through intent-based decision-making""", """<b>An Elegant Puzzle: Systems of Engineering Management</b> by Will Larson — Systems thinking applied to engineering teams and orgs"""]) + mg("Articles & Essays", ["""<b>\"What Staff+ Actually Means\"</b> — StaffEng.com collection of Staff+ engineer perspectives""", """<b>\"How to Be a Staff Engineer\"</b> — Lutz's blog series on bridging Senior to Staff""", """<b>Google's Project Aristotle</b> — Research on high-performing team characteristics""", """<b>\"The Manager's Path\" (sections on Staff+)</b> — Camille Fournier's insights on technical leadership""", """<b>\"Leading Without Authority\"</b> — HBR articles on cross-functional influence""", """<b>Amazon's Leadership Principles</b> — The most explicit corporate leadership framework, applicable across FAANG"""]) + mg("Communities & Practice", ["""<b>StaffEng Slack / Community:</b> Active community of Staff+ engineers sharing experiences and advice""", """<b>Rands Leadership Slack:</b> Leadership community with Staff+ focused channels""", """<b>Engineering Enablement Slack:</b> Community focused on developer productivity and platform engineering""", """<b>Levels.fyi (compare compensation, read promo experiences):</b> Data on promotion timelines and compensation brackets""", """<b>Blind</b> — Anonymous discussions about FAANG culture, compensation, and promotion (take with grain of salt)"""]) + bd("<b>Final Word</b>") + bd("The Staff+ behavioral interview is fundamentally about <b>judgment</b>. Can you make sound decisions under uncertainty? Can you navigate complex organizational dynamics? Can you learn from failure without being diminished by it? Your stories reveal your judgment. Prepare them carefully, deliver them authentically, and let the depth of your experience shine through."),
    "language": "text",
    "sections": [{"heading": "Reader Exercise: Self-Assessment", "content": bd("Before your Staff+ interviews, rate yourself on each dimension and identify your weakest areas:") + tb(["Competency", "Self-Rating (1-5)", "Evidence Needed", "Gap"], [["Influence without authority", "", "Story of cross-team alignment without reporting lines", ""], ["Technical vision", "", "A vision doc that shaped org direction", ""], ["Conflict resolution", "", "Successfully mediated a significant disagreement", ""], ["Mentorship/sponsorship", "", "An engineer you developed who advanced", ""], ["Communication", "", "A document or presentation that aligned stakeholders", ""], ["Decision-making", "", "A high-stakes decision with right reasoning", ""], ["Ambiguity navigation", "", "A project you defined from a fuzzy starting point", ""], ["Failure/learning", "", "A mistake you owned and learned from deeply", ""], ["Technical debt management", "", "Systematic improvement of a legacy system", ""], ["Team building", "", "Improved team health, culture, or processes", ""], ["Cross-functional collaboration", "", "Partnership that produced exceptional results", ""]]) + bd("Focus 80% of your preparation time on the 3-4 areas with the largest gaps. The other areas need to be passable, but your weakest dimension will be the one that gets probed deepest.")}],
    "tags": ["behavioral", "references", "further-reading", "staff-plus", "career"]
})

out = {
    "id": "behavioral-staff",
    "title": "Staff+ Behavioral & Leadership Interview Preparation",
    "category": "behavioral",
    "subcategory": "Staff+ Interview Prep",
    "description": "Comprehensive Staff+ guide covering behavioral interviews, leadership without authority, technical vision, conflict resolution, mentorship, executive presence, decision-making, storytelling, cultural fit (FAANG-specific), failure handling, team building, technical debt management, promotion strategies, and full interview preparation — designed for Staff Engineer (L6/E6) and Senior Staff (L7/E7) interviews at FAANG and top tech companies.",
    "language": "text",
    "sections": [s for s in S],
    "tags": ["behavioral", "leadership", "staff-plus", "interview-prep", "faang", "career"]
}

os.makedirs("content/patterns", exist_ok=True)
path = "content/patterns/behavioral-staff.json"
with open(path, "w") as f:
    json.dump(out, f, indent=2)
    f.write("\n")
sz = os.path.getsize(path)
print(f"Wrote {path} ({sz} bytes, {len(S)} sections)")
for i, s in enumerate(S):
    print(f"  {i+1:2d}. {s['title'][:55]:55s} desc={len(s['description']):>5d}")
