// scripts/build.mjs
// Regenerates js/generated.js from content/ JSON files

import fs from 'fs';
import path from 'path';

const contentDir = 'content';
const outputFile = 'js/generated.js';

function generateHashFromId(id) {
  return '#' + id;
}

function scanContent() {
  const routes = {};
  const searchIndex = [];

  function processDir(dir) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        processDir(fullPath);
      } else if (entry.name.endsWith('.json')) {
        try {
          const data = JSON.parse(fs.readFileSync(fullPath, 'utf8'));
          const id = data.id;
          if (!id) continue;

          const relativePath = path.join(dir, entry.name).replace(/\\/g, '/');
          const hash = generateHashFromId(id);
          routes[hash] = relativePath;

          // Build search entry
          const searchEntry = {
            title: data.title || id,
            category: data.category || '',
            url: `docs.html${hash}`,
            tags: data.tags || []
          };
          searchIndex.push(searchEntry);
        } catch (e) {
          console.error(`Skipping ${fullPath}: ${e.message}`);
        }
      }
    }
  }

  if (fs.existsSync(contentDir)) {
    processDir(contentDir);
  }

  return { routes, searchIndex };
}

function generateJs(routes, searchIndex) {
  const timestamp = new Date().toISOString();
  const routeMapLines = Object.entries(routes)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([hash, filePath]) => `  "${hash}": "${filePath}",`)
    .join('\n');

  const searchIndexLines = searchIndex
    .map(entry => {
      const tags = entry.tags.map(t => `      "${t.replace(/"/g, '\\"')}"`).join(',\n');
      return `  {
    "title": "${entry.title.replace(/"/g, '\\"')}",
    "category": "${entry.category.replace(/"/g, '\\"')}",
    "url": "${entry.url}",
    "tags": [
${tags}
    ]
  }`;
    })
    .join(',\n');

  return `// Auto-generated by scripts/build.mjs — do not edit manually
// Built: ${timestamp}

window.__BUILD_TIMESTAMP = "${timestamp}";

window.__ROUTE_MAP = {
${routeMapLines}
};

window.__SEARCH_INDEX = [
${searchIndexLines}
];
`;
}

function main() {
  console.log('Rebuilding js/generated.js from content/...');
  const { routes, searchIndex } = scanContent();
  const js = generateJs(routes, searchIndex);
  fs.writeFileSync(outputFile, js);
  console.log(`Wrote ${outputFile} (${Object.keys(routes).length} routes, ${searchIndex.length} search entries)`);
}

main();
